### ISSUE TITLE
post-navigation.php does not exist

### ISSUE THREAD

**Issue by yingles** [WordPress/twentynineteen#102]
The `template-parts/posts/post-navigation.php` file referenced in single.php does not exist.

https://github.com/WordPress/twentynineteen/blob/f0b3e8cdb908aa3cb0a7171dde3c749632c51612/single.php#L56

**Comment by yingles** [comment]
It seems the call is not needed since the post navigation is called before this line with `the_post_navigation`.

**Comment by allancole** [comment]
Closing as this is fixed in #101
