### ISSUE TITLE
Styling sticky posts

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentynineteen#104]
Right now, a sticky post is visually not distinguishable from other posts.

Consider adding some specific styling or some kind of label ("featured" as in other default themes, a star (mind accessibility)?, ...) to sticky posts.

**Comment by khleomix** [comment]
@LittleBigThing do you have anything specific in mind with regards to the design of the sticky posts? Twenty Seventeen has a thumb tack icon, Twenty Sixteen and Twenty Fifteen both have the `<span class="sticky-post">Featured</span>`

Are we going to do something similar? @kjellr do we have a design for this? Will take this up.

**Comment by LittleBigThing** [comment]
Nothing specific, @khleomix.

- It could be as little as adding the label "Featured" to the entry meta data under the post, maybe with a star as an icon.
- Or adding a larger (star) icon left to the title in the margin (with sufficient attention to a11y), much like to custom logo can be added next to the site title.
- Or &mdash; and I might prefer this option &mdash; style the **first** sticky post in the list of posts like a single post is styled (also including a 'Featured' label). So, with the wide, full-screen featured image and the post title above it.

I would love to join in helping to realise one of these options or another cool idea.

**Comment by khleomix** [comment]
@LittleBigThing I'll do some mockups tomorrow and we can start from there.

**Comment by khleomix** [comment]
@LittleBigThing here are some mockups, I do prefer having the first sticky post styled like a single post. We'll probably need to set a default background for those that don't have featured images though...

![starred](https://user-images.githubusercontent.com/1948204/47233353-05153100-d405-11e8-94f9-1e231e20a437.jpg)
![post-meta-featured](https://user-images.githubusercontent.com/1948204/47233354-09414e80-d405-11e8-8a0c-b56289a70e1e.jpg)
![post-header-featured](https://user-images.githubusercontent.com/1948204/47233356-0ba3a880-d405-11e8-91e1-ba8968cd85f4.jpg)
![most-recent-featured](https://user-images.githubusercontent.com/1948204/47233360-0d6d6c00-d405-11e8-8143-ee40df9a921e.jpg)

**Comment by LittleBigThing** [comment]
Nice, thanks! I like them all and I prefer also the one that is styled as a single post. Although I am wondering if it isn’t confusing havind the other posts below it. Also, we should determine what we would do if there are more sticky posts.

Anyway, we need probably some design feedback, @kjellr?

**Comment by khleomix** [comment]
@LittleBigThing my thoughts as well, maybe not have it as big? Will have to create another mockup to show this... 

But for the most recent sticky post mockup -  it might be too in your face for some (although I do like that it calls that much attention, it just screams "read me!"), the other sticky posts can have a featured tag at the entry footer meta just like what I have added there. Will need more discussion to move forward.

**Comment by LittleBigThing** [comment]
Hi,

As discussed above, see #201 as a proposal to style sticky posts with the label "Featured" and see a screenshot below.

![screenshot featured sticky post](https://user-images.githubusercontent.com/5901923/47243728-4997d100-d3f3-11e8-9e0a-b292b648c546.jpg)

**Comment by kjellr** [comment]
Closed via #201
