### ISSUE TITLE
Video embed issues

### ISSUE THREAD

**Issue by dartiss** [WordPress/twentynineteen#107]
I added a couple of YouTube oEmbeds, each set to display as wide in Gutenberg. However, they displayed not even responsive, let alone wide, and with massive spaces beneath them. Example screenshot...

<img width="1644" alt="screenshot 2018-10-17 at 10 12 32" src="https://user-images.githubusercontent.com/14928971/47076264-3d92f000-d1f6-11e8-8fef-2c72c2ee9552.png">

Tested on...
WordPress: 4.9.8
Gutenberg: 3.9.0
Jetpack: 6.6.1
Twenty Nineteen: 1.0 (dated October 17th)

**Comment by fabiankaegy** [comment]
How did you add the youtube embed? Did you use the Video block or the HTML Block or the classic editor? 

Using the YouTube block I was not able to replicate the issue.

**Comment by dartiss** [comment]
I've just recreated this again (just to be sure).

I pasted a YouTube URL directly into an empty paragraph block.

**Comment by dartiss** [comment]
Here's the resulting Gutenberg mark-up if this helps at all...

```
<!-- wp:paragraph -->
<p>Line 1</p>
<!-- /wp:paragraph -->

<!-- wp:core-embed/youtube {"url":"https://www.youtube.com/watch?v=fT2pmyuoRyE","type":"video","providerNameSlug":"youtube","align":"center","className":"wp-has-aspect-ratio wp-embed-aspect-16-9"} -->
<figure class="wp-block-embed-youtube aligncenter wp-block-embed is-type-video is-provider-youtube wp-has-aspect-ratio wp-embed-aspect-16-9"><div class="wp-block-embed__wrapper">
https://www.youtube.com/watch?v=fT2pmyuoRyE
</div></figure>
<!-- /wp:core-embed/youtube -->

<!-- wp:paragraph -->
<p>Line 2</p>
<!-- /wp:paragraph -->
```

**Comment by fabiankaegy** [comment]
Okay great thanks. Just tested that again and I can't seem to replicate it.

It also looks like Gutenberg itself added the responsiveness to the plugin in 3.9 
[https://github.com/WordPress/gutenberg/pull/9500](https://github.com/WordPress/gutenberg/pull/9500 ) 

Are you sure you're running the latest release of Gutenberg? 

If that is the case we might need some more testing.

On my install it looks like this: 

![Uploading Bildschirmfoto 2018-10-17 um 11.41.07.png…](Standard Alignement)
![Uploading Bildschirmfoto 2018-10-17 um 11.41.25.png…](Wide Alignement)
![Uploading Bildschirmfoto 2018-10-17 um 11.41.35.png…](Full Alignement)

**Comment by fabiankaegy** [comment]
<img width="1920" alt="bildschirmfoto 2018-10-17 um 11 41 25" src="https://user-images.githubusercontent.com/20684594/47078036-a8e2bf00-d202-11e8-9359-31e740ddf965.png">
<img width="1920" alt="bildschirmfoto 2018-10-17 um 11 41 35" src="https://user-images.githubusercontent.com/20684594/47078037-a8e2bf00-d202-11e8-95ad-af89726472a9.png">
Or with wide and full alignment

**Comment by dartiss** [comment]
Ah. Yes. Another coffee and my memory is working again.

Do you have Jetpack active @fabiankaegy? I think it's related to that (I've seen similar issues with other Gutenberg themes and appears related to a recent change in the way videos are embedded by Gutenberg conflicting with Jetpack embedding).

**Comment by dartiss** [comment]
I've seen this happen with multiple themes either designed for GB or updated for it - I reported it to both Atomic Blocks and Herald, the former has fixed it with some CSS changes. In both cases it was the spacing issue - I've not come across the odd small, left alignment problem.

**Comment by joyously** [comment]
I noticed that a youtube embed was not responsive. I'm not using Gutenberg. 
The video did not have spacing below, but on a narrow window, the video was cut off.

**Comment by kjellr** [comment]
Noting that the Gutenberg team is currently working on making responsive embeds an opt-in for themes:

https://github.com/WordPress/gutenberg/pull/10477

When this is available, we'll certainly opt in to it, and it may solve the issue here.

**Comment by joyously** [comment]
I don't think that's good enough. I don't use Gutenberg and my videos don't look right. The theme should handle it.

**Comment by kjellr** [comment]
Just noting that I tested #442 with the sample content here and it does solve the issue noted above:

![video](https://user-images.githubusercontent.com/1202812/47811968-79ad7100-dd1d-11e8-9519-6096823357b0.gif)
