### ISSUE TITLE
Editor Styles for Latest Categories block 

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/twentynineteen#118]
The somehow children get bigger

<img width="542" alt="bildschirmfoto 2018-10-17 um 16 52 00" src="https://user-images.githubusercontent.com/20684594/47095164-fc6a0280-d22c-11e8-8ebc-cba33ed0f3b7.png">

**Comment by kjellr** [comment]
Thanks, @fabiankaegy — I think there are some inconsistencies in this block's style still (it's seems to be missing missing bullet points for instance), but this particular issue seems to have been resolved at this point. Closing this issue for now. 👍 

<img width="373" alt="screen shot 2018-11-05 at 9 39 06 am" src="https://user-images.githubusercontent.com/1202812/48004253-b7741600-e0de-11e8-923a-bb285da00d1a.png">
