### ISSUE TITLE
Post Navigation aligned wrong

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/twentynineteen#13]
The `.nav-links` element on the Single Blog has a left alignment similar to `.alignwide` blocks. But the right right side has the standard alignment. 

<img width="1808" alt="bildschirmfoto 2018-10-16 um 16 27 28" src="https://user-images.githubusercontent.com/20684594/47023706-81d3b100-d160-11e8-9eeb-bf50afbd51ec.png">

**Comment by kjellr** [comment]
Closed via #21. Thanks!
