### ISSUE TITLE
Post date using relative time

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#131]
The date on a post is shown in relative time (3 minutes) instead of the date format chosen by the user in Settings.

**Comment by kjellr** [comment]
Related to #81. Fix will likely be the same.

**Comment by fabiankaegy** [comment]
I will take the issue  👍

**Comment by kjellr** [comment]
@fabiankaegy I think @briannaorg has this one actually, as per [slack](https://wordpress.slack.com/archives/C02RP4VMP/p1539800591000100).

**Comment by fabiankaegy** [comment]
Oops   👍

**Comment by briannaorg** [comment]
The date shown on posts is the reading length, not the post date. This is a theme feature, so this issue should be closed, but issue #81 should remain open.

**Comment by kjellr** [comment]
Ah! Good catch, thanks @briannaorg. I'm going to close this one in that case. 👍

**Comment by joyously** [comment]
It should be labeled then. And the date should be shown somewhere.

**Comment by briannaorg** [comment]
Agreed. There's an existing twentynineteen_posted_on function to display post dates that's not being called in any template. There's no specific guideline for displaying post dates, so before I open an issue I'm going to review currently open issues and see if it's being discussed.

**Comment by designsimply** [comment]
Note: the decision to remove reading time for now was made in https://github.com/WordPress/twentynineteen/issues/139#issuecomment-431067435 and @briannaorg is working on an update in #168.
