### ISSUE TITLE
Consider changing the reading time calculation to post date instead

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#139]
As discovered in #131, what looks like the post date is actually a reading time.
This needs to be removed, as it is plugin territory.

**Comment by kjellr** [comment]
Adding a screenshot to get us all on the same page: 

<img width="1079" alt="screen shot 2018-10-17 at 8 13 48 pm" src="https://user-images.githubusercontent.com/1202812/47123519-609abf80-d249-11e8-82f6-7d48ec49559b.png">

**Comment by kjellr** [comment]
Thanks for filing this, @joyously. 

Personally, I do not object to including the reading time calculation. I find it useful, and this is not a complicated implementation. The exact placement and treatment used here would be hard to achieve without a very specific plugin that targets Twenty Nineteen specifically. 

When comparing this Reading Time marker to the ["Plugin Territory"](https://make.wordpress.org/themes/handbook/review/required/explanations-and-examples/#plugin-territory) examples in the theme review handbook, my take is that most seem more complicated and/or self contained than this particular feature is. I'd love to hear from others though — specifically those who can weigh in on whether or not this would traditionally be rejected as "plugin" functionality. 

As for the appearance and confusion around what this time is: I think this could be solved by adjusting the label from `X Minutes` to `X minute read`:

<img width="838" alt="screen shot 2018-10-17 at 8 40 11 pm" src="https://user-images.githubusercontent.com/1202812/47124615-db190e80-d24c-11e8-89b8-ff74a4abbb7a.png">

**Comment by joyously** [comment]
It doesn't matter if it's complicated or not, it isn't data that is stored in the database, but computed, and that makes it plugin territory. The user should not lose it when switching themes, which he wouldn't if it was in a plugin.

But it does point to how to make the theme easy to modify. I would suggest the theme use `apply_filters()` on the various parts so that they can be changed or added to. It could be broken down to individual pieces or one filter for the entire meta data line. It could be an action or a filter or both.

**Comment by kjellr** [comment]
Had a good sleep on this, and I agree with you now, @joyously. As we move into phase 2 of Gutenberg, there's even more reason for themes to be purely style-focused. Little bits of functionality like this can (and will) be handled inside of blocks + Gutenberg moving forward. 

So yes, let's remove reading time for now. 👍

**Comment by yingles** [comment]
Just to throw in another argument against, I actually have a reading time plugin on the repo and just got a support request about supporting Hebrew. I haven't delved deep into it yet, but my hunch is that the `str_word_count` function doesn't work well with several languages.

I wanted to bring that up since that's a whole new set of issues to delve into for this functionality in case it works back in.

**Comment by designsimply** [comment]
Thank you for adding screenshots to this issue @kjellr! 😍

**Comment by kjellr** [comment]
Closed via #168
