### ISSUE TITLE
Featured image block is displayed when Homepage is set to 'Your latest post'

### ISSUE THREAD

**Issue by enodekciw** [WordPress/twentynineteen#148]
![image](https://user-images.githubusercontent.com/2080743/47151556-bf604780-d2e2-11e8-812a-8b9970e96c73.png)

I think that #135 introduced this strange behaviour and now when I select 'Your latest posts' as a homepage view, it shows this blue block with the title of my last post.

Also, if I set my homepage to 'a static page' then this issue also appears on a page set as a posts page.

![image](https://user-images.githubusercontent.com/2080743/47151765-46adbb00-d2e3-11e8-95b3-80a0f60e1d47.png)

**Comment by fabiankaegy** [comment]
Good catch. Sorry about introducing that error.

**Comment by joyously** [comment]
The search page was doing this also, when the first post had a featured image. I mentioned that in the PR to clean up the search.

**Comment by kjellr** [comment]
> The search page was doing this also, when the first post had a featured image. I mentioned that in the PR to clean up the search.

That's right. @enodekciw can you retest? I think https://github.com/WordPress/twentynineteen/pull/68 may have sorted this one out.

**Comment by enodekciw** [comment]
Yup, works fine now.
