### ISSUE TITLE
Primary color set in Customizer to affect all elements. 

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/twentynineteen#149]
I think all the elements that currently use the color `#0073aa` (Blue) should be changed using the Customizer.  

### Frontend: 
- [x] Featured Image
- [x] Post Thumbnail
- [x] Menu Item
- [ ] Menu Item Hover
- [x] Link Color ? 
- [ ] Link Color Hover
- [x] Button Color 
- [x] Pullquote left Border 
- [x] Post Navigation - Post Title 

### Customizer: 
- [x] Featured Image
- [x] Post Thumbnail
- [x] Menu Item
- [ ] Menu Item Hover
- [x] Link Color ? 
- [ ] Link Color Hover
- [x] Button Color 
- [x] Pullquote left Border 
- [x] Post Navigation - Post Title 

### Editor: 
- [ ] Link Color ? 
- [ ] Link Color Hover
- [ ] Button Color 
- [ ] Pullquote left Border 

This is supposed to extend the work of #113

**Comment by fabiankaegy** [comment]
If that's ok I can take the issue and work on that. 

### Question
@kjellr there are some areas, like for example the link / menu Item color that are set using the sass function `darken()`. How should we go about setting those via plain css? Should we add a php function to mirror the behaviour of `darken()`?

**Comment by fabiankaegy** [comment]
<img width="281" alt="bildschirmfoto 2018-10-18 um 14 38 08" src="https://user-images.githubusercontent.com/20684594/47154756-79f04a00-d2e3-11e8-8df8-f5a6c17aa486.png">
And I believe there either should be some warning message like in Gutenberg when the color doesn't have enough contrast to other elements, or some functionality that for example determines the font color on a button automatically based on the new background color.

**Comment by killermann** [comment]
I just forked the theme and started working on exactly this, before checking the open issues. Let me know if you want help testing, @fabiankaegy.

**Comment by fabiankaegy** [comment]
@killermann this is my current state: https://github.com/fabiankaegy/twentynineteen/tree/feature/primary-color-customizer I still need to add the editor styles and the functionality to warn users if there isn't sufficient contrast. Do you want to take up one of these things?

**Comment by fabiankaegy** [comment]
And I'll open the pull request now so you can just have a look here. I'm happy for all the feedback I can get

**Comment by fabiankaegy** [comment]
@allancole would you just add separate controls for the primary and hover color or for each element separately?

**Comment by designsimply** [comment]
Aha! I spotted a duplicate issue at https://github.com/WordPress/twentynineteen/issues/191 where we didn't catch that this issue was open first, and @fabiankaegy I see that you've asked your question about whether or not to use separate controls for primary and hover colors there already. 

Let's consolidate to #191! (but still keep using this thread for the checklist if it's helpful to your own workflow)
