### ISSUE TITLE
show .site-description only if $description is not empty

### ISSUE THREAD

**Issue by enodekciw** [WordPress/twentynineteen#17]
At the moment .site-description in template-parts/header/site-branding.php is always visible. On is_home() or is_front_page() it displays the description of the website, however on other pages it will only display the seperator (&mdash;)

**Comment by joyously** [comment]
Don't you need to display it for `is_customize_preview()` also?

**Comment by enodekciw** [comment]
It is there when you're customizing `is_home()` or `is_front_page()`.

**Comment by enodekciw** [comment]
Oh, took me one browser refresh to see what you meant :)

Clearing out the input, publishing changes and only then refreshing the Customizer, made that pencil icon to disappear. Thanks for noticing this, @joyously! (not an experienced user of Customizer myself, sorry!)

I've updated the PR, should be working fine now - added in a conditional statement which checks if $description is not null when `is_customize_preview()`.
