### ISSUE TITLE
Convert `contributors.md into a table supporting GitHub and WordPress.org usernames

### ISSUE THREAD

**Issue by ntwb** [WordPress/twentynineteen#172]
Ref: https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTORS.md

Unfortunately, not everyone has the same username on GitHub and WordPress.org

As such listing both users usernames for both platforms is beneficial when _props_ time comes around.

#Good-First-Issue

**Comment by pratikthink** [comment]
Update WordPress.org Username in CONTRIBUTORS.md #11328

**Comment by allancole** [comment]
Closing as this is addressed in #309
