### ISSUE TITLE
Update the `.editorconfig` file to use latest from core

### ISSUE THREAD

**Issue by ntwb** [WordPress/twentynineteen#173]
The `.editorconfig` file added in #167 was not the latest version of the file.
> https://github.com/WordPress/twentynineteen/blob/master/.editorconfig

It should be updated to the latest from core:
> https://core.trac.wordpress.org/browser/trunk/.editorconfig

#Good-First-Issue

**Comment by brandonpayton** [comment]
Thanks for catching that, @ntwb.
