### ISSUE TITLE
iframes not centered in content

### ISSUE THREAD

**Issue by eliorivero** [WordPress/twentynineteen#175]
### Context

An article originally authored with the classic editor has this Instagram post, embedded using the regular link paste/embed functionality

https://www.instagram.com/p/BkAUuELlveW/?taken-by=eliorivero

### Expected

iframe to be centered

### Result

iframe was positioned towards left

<img width="919" alt="captura de pantalla 2018-10-18 a la s 23 19 23" src="https://user-images.githubusercontent.com/1041600/47194101-7634e580-d32c-11e8-9ab3-97c2d7aee5d3.png">

### Notes

While I see there is styling applied to iframes in general in [_media.scss](https://github.com/WordPress/twentynineteen/blob/be850d11ee31434ad700db518ff8570f82e65b9c/sass/media/_media.scss), this is not applied to this iframe because Instagram posts have some inline styles in the iframe.

**Comment by nielslange** [comment]
@eliorivero I've created #185 to fix this issue. 🤞that it'll get merged soon-ish. 😉

**Comment by eliorivero** [comment]
Thanks @nielslange!
