### ISSUE TITLE
make the theme as lightweight as possible

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentynineteen#181]
Lightweight themes can load fast without spending hours optimising them by adding stuff. With WordPress powering over 30% of all websites, a lightweight theme can make a real difference in sustainable web development. With Gutenberg, it will be easier to create richer layouts without using more complicated and often bloated solutions. This default theme could demonstrate best practice on this area. And seems that it is off to a good start.

Here, we could gather some suggestions to keep/make Twenty Nineteen as lightweight as possible without losing essential features and functionality.

To start with, here are some suggestions:
- jQuery is not used for now, let's keep it this way: **check**
- do not use webfonts: **check**
- use progressive enhancement, of course
- use polyfills to account for essential functionality in non-supporting browsers
- ...

**Comment by ianbelanger79** [comment]
- Use just vanilla CSS instead of SASS, as is being discussed in #30

**Comment by kjellr** [comment]
Thanks for the reminder, @LittleBigThing! 

These are absolutely great points, and keeping the theme lightweight is an important goal. As you noted, this was the driving force behind the theme's reliance on system fonts (and the fact that we don't — and have no plans to use — jQuery). 🙂 Making use of progressive enhancement and accounting for similar or equivalent functionality across our [supported browser set](https://make.wordpress.org/core/handbook/best-practices/browser-support/) is also key. 

You can help by: 

- Identifying areas where we're currently _not_ fulfilling the needs you mentioned above. Your issue #121 is a great example of this. 🙌
- Looking for specific areas of improvement in our codebase, and proposing solutions. For example, (I haven't had a chance to review yet, but) #39 and #47 are great examples of PRs aimed at being smarter about the loading of scripts.

Identifying these issues + opportunities at an early stage is essential to making them happen.

**Comment by LittleBigThing** [comment]
Check out the [latest update](https://github.com/WordPress/twentynineteen/pull/450#issuecomment-435398036) for  #450 as an enhancement, related to this issue.

**Comment by kjellr** [comment]
👋 Since this is more of a point of feedback than an addressable issue, I'm going to close it rather than port it over to Trac. 

Thanks for helping us keep the theme lightweight and speedy, @LittleBigThing!
