### ISSUE TITLE
Fixed audio player overlaping post/page container

### ISSUE THREAD

**Issue by mmaumio** [WordPress/twentynineteen#198]
Using self-hosted Audio file with audio shortcode using Media Element js on any post/page overlaps the entire post/page content area.

**Comment by mmaumio** [comment]
Provided a fix here.
#197

**Comment by kjellr** [comment]
Adding a screenshot for reference: 

![screen shot 2018-10-19 at 4 07 45 pm](https://user-images.githubusercontent.com/1202812/47242500-e55a1a80-d3bc-11e8-91cb-674f56f06afd.png)

**Comment by mmaumio** [comment]
Thank You @kjellr 
I should have added a screenshot with some other details to replicate it though.

Please let me know if it fixes the issue or there's anything else I should take care of here.

**Comment by kjellr** [comment]
Closing via #185
