### ISSUE TITLE
Improve link styling 

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentynineteen#205]
In #186 we've decided to style the links within the content using `text-decoration: underline;` for now. This issue is a working draft for discussions to change this behaviour in the future.

**Comment by allancole** [comment]
Closing this since a fix was merged in #186

**Comment by nielslange** [comment]
@allancole The intention of this issue was to have a discussion about potential improvements as mentioned by @melchoyce in https://github.com/WordPress/twentynineteen/pull/186#issuecomment-431418217. Thus, to have a discussion if the links should be styled differently in the future. Thus, this issue is separate than #186. But to keep this clean, I'm happy with having this issue closed. 😉

**Comment by kjellr** [comment]
> But to keep this clean, I'm happy with having this issue closed. 😉

Agreed — this isn't going to make it into RC1, but after that, we can open a ticket for this on Trac if we have  a specific idea to pursue.
