### ISSUE TITLE
readme and version required

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#207]
Current usage is that themes do not have a "Requires at least" tag.
There are core tickets open to add it, and also tickets to add a standard readme file to themes (instead of just using style.css headers).
This theme's readme.md has "Requires at least  4.9.8", but it actually only requires 4.9.6 because of  `the_privacy_policy_link()`. Beyond that, it only needs 4.5 for the custom logo.
Is something else going to be added from 4.9.8?

**Comment by joyously** [comment]
This issue was closed Oct 22, but a new theme review requirement was added on Oct 25 regarding readme files.
https://make.wordpress.org/themes/2018/10/25/new-requirements/

So, the readme file has the wrong name, and a bit of the wrong format.

**Comment by kjellr** [comment]
Thanks for the heads up, @joyously — I'll open a new, separate issue for that one.
