### ISSUE TITLE
post_thumbnail size assumes large images

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#208]
When viewing a post with a small featured image, the CSS causes the browser to upscale the image and it looks jagged and bad. It also takes up way too much space (it's a vertical image).
I think that the CSS should never use width:100% on images, because the CSS can't know what size they are.

**Comment by kjellr** [comment]
For visual reference, here's a screenshot using a tiny 80px by 60px featured image:

<img width="1440" alt="screen shot 2018-10-19 at 11 02 24 pm" src="https://user-images.githubusercontent.com/1202812/47250651-2705b800-d3f3-11e8-882c-f3e109c150e8.png">

**Comment by nielslange** [comment]
@joyously & @kjellr On the other hand, having an 80x60 pixel featured image doesn’t look good either. Would it be a better approach to request a minimum height/width for the featured image?

**Comment by joyously** [comment]
The one I had on my test site wasn't that small, but still it looked bad. And you can't enforce anything for legacy content. You could put a different class on it if it is below a threshold.
When I found this, I disabled the `width:100%` rule and the small image was repeating. It didn't look too bad that way...

**Comment by kjellr** [comment]
I did some exploration around this today, and did not arrive on a great solution to this issue. Here are  some examples, each using one large image (`2520×1415`), one medium (`640x480`), and one small (`160x160`). I added some quick analysis based on my own personal impression of each option. 

## Option 1: Current

Large: 
![01-large](https://user-images.githubusercontent.com/1202812/47933954-64b31800-deac-11e8-815f-0551c89a3064.png)

Medium:
![01-medium](https://user-images.githubusercontent.com/1202812/47933956-67157200-deac-11e8-97fd-228201409841.png)

Small:
![01-small](https://user-images.githubusercontent.com/1202812/47933958-6a106280-deac-11e8-9236-71123464da01.png)

✅ Great: Large image looks ideal.
✅ Great: Medium image looks good, if not very slightly fuzzy. 
🆗 Small image is pixellated, but fills the screen.  

## Option 2: Contain

Large:
![02-large](https://user-images.githubusercontent.com/1202812/47934052-a8a61d00-deac-11e8-815a-f45fa9f29a67.png)

Medium:
![02-medium](https://user-images.githubusercontent.com/1202812/47934059-acd23a80-deac-11e8-98fa-4fde6f3f7875.png)

Small:
![02-small](https://user-images.githubusercontent.com/1202812/47934068-afcd2b00-deac-11e8-9d6d-8c43f3d37cbf.png)

✖️ Large image has borders. Appears broken.
✖️ Medium image has borders. Appears broken.
✖️ Small image is pixellated, has borders. Appears broken.

## Option 3:  Do Nothing

Large:
![03-large](https://user-images.githubusercontent.com/1202812/47934164-02a6e280-dead-11e8-928b-86652225de33.png)

Medium:
![03-medium](https://user-images.githubusercontent.com/1202812/47934177-08042d00-dead-11e8-83c4-5a6678027a1e.png)

Small:
![03-small](https://user-images.githubusercontent.com/1202812/47934178-0a668700-dead-11e8-8de1-567aa329ae0a.png)

🆗 Large image is very zoomed in, missing details. 
✖️ Medium image has a frame around it. Appears broken. 
✖️ Small image is not pixellated, but has a frame around it. Appears broken.

##  Option 4: Repeat
_This method is  not compatible with #450._

Large:
![04-large](https://user-images.githubusercontent.com/1202812/47934480-bd36e500-dead-11e8-98ed-e5a4622eeb40.png)

Medium:
![04-medium](https://user-images.githubusercontent.com/1202812/47934485-c031d580-dead-11e8-94ee-c49f8658b5de.png)

Small:
![04-small](https://user-images.githubusercontent.com/1202812/47934487-c2942f80-dead-11e8-8197-50cb83e5e142.png)

🆗 Large image is very zoomed in, missing details. 
✖️ Medium image _almost_ fits, but doesn't quite. The repetition is confusing in this case. 
🆗  Small image is not pixellated, but the repetition is more clear.

---

We could also technically target smaller images and give them a different treatment than larger images, but I worry that'd be confusing for users. 

These results would vary depending on the types of images used  and their subjects. That said, our current approach results in reasonable (or better) behavior when using the greatest variety of image sizes, so I'd prefer to continue with that at this point. I'm going to leave this issue out of RC1 for now, but if a PR arises with a good solution that works across all image sizes we'll happily fast-track it.

**Comment by kjellr** [comment]
Just wanted to note that I did explore a separate option to solve this problem by adding a toggle for the full screen featured images:  

![full-screen-image](https://user-images.githubusercontent.com/1202812/49031577-5341f080-f178-11e8-9e73-bd2cd9461eaa.gif)

However, that change relies on implementing a new feature. Now that we're in RC1, we aren't going to be undertaking any design tweaks of that size. That solution is [archived here](https://github.com/WordPress/twentynineteen/pull/672) in case anyone wants to work with it in the future, but @allancole and I won't be incorporating it into the initial release.

The theme was designed for featured images to appear full-screen, like they are currently. So ruling the theme toggle out, we're already using the next best solution we have at this point (based on [the explorations shared above](
https://github.com/WordPress/twentynineteen/issues/208#issuecomment-435475734) at least), so I'm going to go ahead and close this issue for now. If a better solution arrives between now and release, we'll consider it, but the current behavior is working as designed.
