### ISSUE TITLE
page links run together

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#209]
The page links are a little close together, so it looks like one number. Perhaps use more space or commas between them?

![page-links](https://user-images.githubusercontent.com/7957680/47250198-3e3ca980-d3e3-11e8-8452-699fea259e77.jpg)

**Comment by nielslange** [comment]
@joyously and @kjellr How have you been able to see the pagination including the label _Pages_? This is what I see when looking up the pagination on the blog posts page:

<table>
<tr>
<td valign="top">iPhone X:

![209 - before iphone x](https://user-images.githubusercontent.com/3323310/47326446-022f7000-d693-11e8-9ed0-ed7141b942f1.png)</td>
<td valign="top">iPad:

![209 - before ipad](https://user-images.githubusercontent.com/3323310/47326445-0196d980-d693-11e8-8834-cddc497182df.png)</td>
<td valign="top">iPad Pro:

![209 - before ipad pro](https://user-images.githubusercontent.com/3323310/47326443-00fe4300-d693-11e8-90d4-9cd9e39dcbc3.png)</td>
</tr>
</table>

**Comment by kjellr** [comment]
@nielslange: In Gutenberg,  try adding a `pagination`  block within a post to see this pagination.

**Comment by nielslange** [comment]
Thanks, @kjellr! I'll check that later!

**Comment by joyously** [comment]
It's not pagination on the blog, it's page links in a post or page, which is generated from the `<!--nextpage-->` tag by the theme.

**Comment by nielslange** [comment]
Thanks for the additional info, @joyously. I'm already on it. 😉
