### ISSUE TITLE
Placement of comment user avatar/gravatar is off

### ISSUE THREAD

**Issue by khleomix** [WordPress/twentynineteen#213]
This only happens on posts/pages that don't have comments yet. The comment user avatar's placement is off and covers the top part of the comment form. Happens on both logged out and logged in users.

![comment-logged-out](https://user-images.githubusercontent.com/1948204/47256396-66470e00-d4b2-11e8-9bb1-51cada06a12d.png)
![comment-logged-in](https://user-images.githubusercontent.com/1948204/47256397-6810d180-d4b2-11e8-8398-e8810aeb35ef.png)

**Comment by khleomix** [comment]
@nielslange right, but that rule set is only followed by posts that have comments already. This is superseded by this part from the same file:

```
#comments {

	> .comments-title:last-child {
		display: none;
	}

	> #respond {
		@include media(desktop) {

			.comment-user-avatar {
				position: absolute;
				display: block;
				top: 0;
				left: 0;

				.avatar {
					display: block;
				}
			}
		}
	}
}
```

I've tested in firefox, chrome, opera with cache cleared and all show the same issues.

**Comment by khleomix** [comment]
@nielslange should we really show an avatar before a comment is made though? Twenty Seventeen, Twenty Sixteen, and Twenty Fifteen do not show the avatar for both logged and logged out users. Having an avatar showing for those that aren't logged in is confusing as it will show the default mystery man...

**Comment by nielslange** [comment]
@khleomix Thanks for reporting this issue. I just created the fix #214. Let's hope it'll get merged soon-ish. 

I just saw your reply to my message, which I've already deleted. I found out that Gravatars are hidden if the screen is smaller than 1168px. I should not have deleted my comment but marked it as solved. Sorry in case this caused some confusion. I think it indeed makes sense to hide the Gravatar completely for non-logged in users.

@allancole While analysing this issue, I found out that the Gravatar above the comment form is only visible on screens with a minimum width of 1168px. Also, I like @khleomix suggestion of removing Gravatar completely for non-logged in users, to retain consistency with the other themes of the Twenty series. I saw that you made the initial commit of the corresponding *.sass file. 

Can you clarify where the visibility statement is based on? Also, please let me know if we should hide it for non-logged users and if we should show if for logged in users on all screen sizes.

**Comment by khleomix** [comment]
no worries about the comment :) 

Also, you might want to look at these screenshots as well... The avatar list is not really working and it looks off... The `discussion-meta-info` with `1 response from 1 other.` is confusing and I don't really get why that is worded that way.

I can create a separate issue for this but since it's all part of the comment avatar functions in this file https://github.com/WordPress/twentynineteen/blob/master/inc/template-tags.php maybe it can be part of one fix? But if not, let me know. Dropping the screenshots here for reference:

![avatar-list-header](https://user-images.githubusercontent.com/1948204/47257494-276c8480-d4c1-11e8-9178-7d7f3f1627f4.png)

![avatar-list-comments](https://user-images.githubusercontent.com/1948204/47257496-2b98a200-d4c1-11e8-89b1-ac90b5eafb41.png)

**Comment by allancole** [comment]
> Also, you might want to look at these screenshots as well... The avatar list is not really working and it looks off... The discussion-meta-info with 1 response from 1 other. is confusing and I don't really get why that is worded that way.

So the idea behind displaying a commenter avatars list is to try and encourage more discussions. It’s a fairly common pattern, used by Instagram, Medium, and a few others to give visitors a visual hint about who has commented on a post. I’d love to keep this in, but I think you’re right about the wording being unclear. I’d be okay if it were changed to something more common, like a simple comments count. 

> Should we really show an avatar before a comment is made though? 

> Can you clarify where the visibility statement is based on? Also, please let me know if we should hide it for non-logged users and if we should show if for logged in users on all screen sizes.

Honestly, this is a design oversight. It isn’t really useful to have an avatar visible when you’re not logged in, so let’s go ahead and remove it and squash this bug 👍

**Comment by khleomix** [comment]
@allancole I figured that’s where we’re going with the avatar list, it’s not working though and only shows the first commenter’s avatar. It would be great if we can get it to work but the wording needs to change. Maybe have it the same as what is in the entry-header part?

**Comment by allancole** [comment]
> Maybe have it the same as what is in the entry-header part?

Yup, I think that’s the best and simplest way forward.

**Comment by mmaumio** [comment]
I figured out the issue on my end as well and found out the thread eventually.
Attached the screenshot if that helps in anyway.
![screenshot 2018-10-22 at 1 58 11 pm](https://user-images.githubusercontent.com/3687038/47282834-8980d300-d602-11e8-97cf-e45472307c23.png)

Also, I'm sure you are aware that changing the #comments > #respond .comment-user-avatar position from absolute to relative fixes it for the time being. :)
