### ISSUE TITLE
Fixed product layout broken in search result archives page.

### ISSUE THREAD

**Issue by mmaumio** [WordPress/twentynineteen#223]
Create few products and search with a keyword to see the product post layout broken.
Screenshot added for reference.
![screenshot 2018-10-21 at 4 42 36 am](https://user-images.githubusercontent.com/3687038/47261210-1dac4680-d4ec-11e8-94db-d72087ffb1c4.png)

Fixed here: #222

**Comment by joyously** [comment]
Is this just because the margin is not applied for unknown post types?

**Comment by allancole** [comment]
I think we’ll end up adding an `.entry` class to _all_ post types to deal with this issue and the concerns mentioned here: https://github.com/WordPress/twentynineteen/issues/74

**Comment by mmaumio** [comment]
@allancole Would you like me to try this? 
What I have understood is, we'll remove the hentry class and push an entry class to the post class of every posts regardless of the product or any other custom post type.
Then write the css of "hentry" to the "entry" class.

Is that correct?

Thank You

**Comment by joyously** [comment]
> we'll remove the hentry class

Don't add or remove the `hentry` class. _(Well, except that it shouldn't be on Pages, but that might be a different issue.)_ 
Add `entry` class to all posts.
Change CSS that refers to `hentry` to instead use `entry`.

**Comment by allancole** [comment]
@mmaumio, @joyously is mostly correct. 

To clarify:

• Don't add, change or remove the `.hentry` class.
• Use the `add_filter( 'post_class', '...' )` filter to add the `.entry` class to _all_ post-types.
• Change any CSS selectors that use `.hentry` to use `.entry`, instead.

**Comment by mmaumio** [comment]
That's great.
I'm on it.

Thanks

**Comment by mmaumio** [comment]
Made the changes recommended.

**Comment by WPprodigy** [comment]
Linking to the PR for search-ability: https://github.com/WordPress/twentynineteen/pull/229

**Comment by allancole** [comment]
@mmaumio This should be fixed in #316 so I’ll close this for now. If you still see the problem feel free to reopen or start a new issue.

**Comment by mmaumio** [comment]
Sure.
I'll let you know.

Thank You
