### ISSUE TITLE
remove unneeded background featured image

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentynineteen#234]
The theme displays featured images differently on list pages and on singular ones.

On singular page (post and page), a featured image is displayed as a background image. The image is added in [`functions.php`](https://github.com/WordPress/twentynineteen/blob/1d47dac733db1e373929674e5d3eaefc700e961a/functions.php#L142) via the function [`twentynineteen_header_featured_image_css()`](https://github.com/WordPress/twentynineteen/blob/1d47dac733db1e373929674e5d3eaefc700e961a/inc/template-tags.php#L166).

On list pages (index and archives), the featured image is displayed as an `<img>`. This image is wrapped in an `<a>` element to link to the single post. However, this link has an additional background image of the featured image. This background image is removed in a related PR.

**Comment by kjellr** [comment]
Closed via #233
