### ISSUE TITLE
Sync up margins, line-length between frontend and editor

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#236]
#22 introduced greater visual consistency between the front and back end. However, it can be improved. We should take another pass at making sure both the editor and front end render line-lengths and margins similarly across common breakpoints. 

**Current state:**

![artboard 0](https://user-images.githubusercontent.com/1202812/47298468-defab700-d5e5-11e8-9acd-504ea56b5092.png)

![artboard 1](https://user-images.githubusercontent.com/1202812/47298471-e0c47a80-d5e5-11e8-90d3-edbac161625d.png)

![artboard 2](https://user-images.githubusercontent.com/1202812/47298474-e28e3e00-d5e5-11e8-8494-f8245e944e56.png)

**Comment by LittleBigThing** [comment]
I think that we also need some additional margin (left and right) for fully aligned columns.

Something like

```
.wp-block-columns {
		
	&.alignfull {
		margin-left: $size__spacing-unit;
		margin-right: $size__spacing-unit;
	}
}
```

in `blocks.scss`.

Only for the columns wrapper I think. This way we'll still have margin-less fully aligned image and other.

**Comment by LittleBigThing** [comment]
An example of margin-less columns (open image to see the actual problem):

<img width="1280" alt="screenshot 2018-11-06 at 09 12 52" src="https://user-images.githubusercontent.com/5901923/48051046-3aab6f80-e1a4-11e8-8a58-826e57c10b9d.png">

**Comment by kjellr** [comment]
#502 auto-closed this, but I there's still a bit more work to do for this one: Matching up margins on smaller screens. 

@LittleBigThing: The more I think about the columns issue, I think that should be addressed separately since it's about dealing with that specific single block. Mind opening a separate issue for that one?
