### ISSUE TITLE
Discussion Avatar List not consistent on logged in and logged out views

### ISSUE THREAD

**Issue by khleomix** [WordPress/twentynineteen#238]
The discussion avatar list is not showing the logged in user's avatar and comment is not counted as well. It should follow the logged out view where it shows the post author's avatar and comment count showing the correct count as well. 

Logged in view:
![avatar-list-loggedin](https://user-images.githubusercontent.com/1948204/47304955-a648f500-d65a-11e8-8ea1-2c32ea8f40b2.png)

Logged out view:
![avatar-list-loggedout](https://user-images.githubusercontent.com/1948204/47305020-cf698580-d65a-11e8-97d7-e83dce94b4a4.png)

See #213 for additional info

**Comment by WPprodigy** [comment]
I'm not so sure this is a bug / unintended. The language is "X responses from X others", so it leaves out the currently-logged in user's count on purpose.

This can be seen in `twentynineteen_get_discussion_data()`: https://github.com/WordPress/twentynineteen/blob/7eb93d5f79eedb168f72ccfeddbfcf6f0f129875/inc/template-functions.php#L150

**Comment by crunnells** [comment]
I discussed this issue with @allancole and his thoughts were to trim this down to say "X responses" and from "from Y others". I suggested we _not_ exclude the author from showing in the avatar list, because it's a good way to see if you've replied to other comments on a post or not.

**Comment by WPprodigy** [comment]
Hmm, not sure I follow.

So if there are 4 responses and 3 people involved (including your 1 reply), it should say:

> 4 responses from 2 others

Because that seems a bit odd to me, as the 4 responses aren't all from the 2 others.

**Comment by crunnells** [comment]
The idea is to change it so it says "4 responses" and omit the number of people in the conversation.

**Comment by WPprodigy** [comment]
I think this introduced a new bug related to this: https://github.com/WordPress/twentynineteen/pull/367/files#diff-1cc0a2eb5e0be1a17d62b9ce5d17cf41R169. Unsure of the full context on this change though, CC @allancole as I think it might have been a debugging typo.

**Comment by kjellr** [comment]
Closing since #525 has been merged. Thanks, everyone!
