### ISSUE TITLE
Footer credit links are in the wrong order

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentynineteen#24]
Currently the privacy policy link sits between the site title and the WordPress credit link,  so it looks like the privacy policy is proudly powered by WordPress:

Theme test, Privacy Policy	Proudly powered by WordPress.

The privacy policy link needs to be moved, and/or dividers need to be added.

**Comment by joyously** [comment]
Or don't put the Privacy Policy link in there for the user.

**Comment by asharirfan** [comment]
@nielslange How about changing the separator from comma `,` to a slash `/` and not moving the position of the _Privacy Link_? 🤔 

Like this:

> WordPress Develop / Privacy Policy / Proudly powered by WordPress.

Because now it is just sitting at the end like this:

> WordPress Develop, Proudly powered by WordPress. Privacy Policy

I would love to push a commit, if you want 🙌

Cheers ✌️

**Comment by carolinan** [comment]
Are forward slashes used as a design element anywhere else in the theme?

Maybe a line more similar to the one used in the header and the navigation, or would that be confusing?
 (The lines would need to be shorter)

**Comment by kjellr** [comment]
@nielslange: Let's just add some empty space to the left of the Privacy Policy link:

![screen shot 2018-10-17 at 3 36 00 pm](https://user-images.githubusercontent.com/1202812/47111778-71840a80-d222-11e8-90f4-e2429c1e5562.png)

You can mirror the spacing used in between post meta in the post footers (I believe it's `1rem`): 

![screen shot 2018-10-17 at 3 34 31 pm](https://user-images.githubusercontent.com/1202812/47111794-8365ad80-d222-11e8-8a2d-dda7609e1eea.png)


Thanks!

**Comment by nielslange** [comment]
@kjellr I just added the space, as suggested, and committed the change in #115.
