### ISSUE TITLE
Support Custom Headers and Video Headers?

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentynineteen#243]
Let's consider adding support for custom headers. If we do, we could also support video headers.

The custom header could be off by default. Or, it could be on and include a compelling default image that ships with the theme. When used, it would match the display of featured images on single pages and posts (with the blue overlay). Perhaps it could be disabled in lieu of the featured image when a static front page is in use. This seems like a great opportunity to unify the single view and homepage view designs visually and functionally.

Video headers were added to core as part of the improvements with Twenty Seventeen. The theme-support implementation [is very straightforward](https://core.trac.wordpress.org/changeset/38985#file9). This could act as a nice preview of future Gutenberg support for featured videos on individual posts and pages, and set Twenty Nineteen up for handling that type of feature design-wise.

**Comment by kjellr** [comment]
There's an open PR to add custom header support (#133), but there's no issue for it, so this one can serve that purpose. 🙂

Video headers could be a nice enhancement, but I'd consider that somewhat low priority while we focus on tailoring the theme to current Gutenberg functionality. If someone would like to open a PR using code ported over from Twenty Seventeen though, I'll happily review and we can get that in.

**Comment by celloexpressions** [comment]
I added the code for that to the header PR, since it's tied together as the same feature. Not sure what the preferred workflow would be to collaborate on that, but I tried to add all of the code with comment so that it's easy to add.

I would note that it's very easy to support video headers since `the_custom_header_markup()` is already being used. See https://make.wordpress.org/core/2016/11/26/video-headers-in-4-7/.

The only other step is to style the play and pause buttons - I will defer to the theme designer on the best approach for that.

**Comment by kjellr** [comment]
The PR related to this issue (#133) was closed a few weeks ago, so we could put the customization focus on Gutenberg, not features like custom headers. See @allancole's notes here: https://github.com/WordPress/twentynineteen/pull/133#pullrequestreview-171791082

As a result, I'm closing this issue as well. Thank you for your contribution!
