### ISSUE TITLE
Links placed in Social Menu Area to open in new tab.

### ISSUE THREAD

**Issue by robeyl** [WordPress/twentynineteen#247]
I quite like how the menu items in the Social Menu area automatically get their icons based on the URL, but they should also open in a new tab by default IMO. 

Not sure how easy that is to do based off their Menu Area, but it's what I would expect to happen when clicking an external link, which these would be in 99% of cases.

**Comment by psaikali** [comment]
Not sure about this. IMHO this is already a core logic that could (or could not) be set by user:

[ie](http://media.mosaika.fr/295fc20631e7/%255B04a908ee980b86d2773bc36e7426ee41%255D_Capture%2525202018-10-23%252520a%2525CC%252580%25252013.44.19.jpg)

But I do agree that the automagic-social-icon based on the menu item URL is super neat 👍 !

**Comment by robeyl** [comment]
Yeah, but first you have to know to look in the hidden 'Screen Options' tab to enable that tickbox.

**Comment by psaikali** [comment]
Indeed, but that is not the theme responsibility to force that kind of setting. I might be wrong though!

**Comment by kjellr** [comment]
I agree with @psaikali here. Though this would generally make sense for social links, it doesn't quite make sense to implement on the theme level. Going to close for now, but we can always re-open in the future, so feel free to keep discussing.

**Comment by 00travelgirl00** [comment]
Please don't open links in new tabs by defailt, as it is not accessible. Please read also the A11y-Handbook for this: https://make.wordpress.org/accessibility/handbook/content/link-destinations/
