### ISSUE TITLE
Add archive descriptions

### ISSUE THREAD

**Issue by DannyCooper** [WordPress/twentynineteen#256]
If https://github.com/WordPress/twentynineteen/pull/255 is merged, then there will need to be a discussion on adding archive descriptions and the design of them.

Archive descriptions are currently filtered so they don't show.

https://github.com/WordPress/twentynineteen/blob/d49b0986cf292c1c3f3a21c36b93814d394fdd36/inc/template-functions.php#L107

**Comment by kjellr** [comment]
I suggest we rework that area to include descriptions like so: 

<img width="609" alt="screen shot 2018-10-24 at 12 37 11 pm" src="https://user-images.githubusercontent.com/1202812/47446596-8e23c380-d789-11e8-9936-06acaa3a887d.png">

This mimics the header text hierarchy a bit. 

- `Category Archives` label becomes `display: block`, takes on our small gray system text style (as used in post meta)
- `Category Name` stays as it would be in #255, but is now `inline-block`
- `Category Description` would be treated in our gray serif text style.

**Comment by mrwweb** [comment]
Why was the archive description removed in the first place? I've got [a plugin](https://wordpress.org/plugins/post-type-archive-descriptions/) that relies on those being present for it to work with a theme out of the box. It seems quite harmless to include. Could we please put it back into `archive.php`?

**Comment by DannyCooper** [comment]
@mrwweb The original design didn't output an archive description, it had the archive title in that position: https://wordpress.slack.com/archives/C02RP4VMP/p1540302375000100

**Comment by mrwweb** [comment]
That's really odd. I realize it's not in the theme requirements to include the archive description, but it does mean that taxonomy term descriptions (a core feature) aren't compatible with Twenty Nineteen. That's bad for SEO and just generally confusing to me.

Is it too late to put it back in? I couldn't find any actual reference to the description and whether or not to include it when I read the linked Slack chat.

**Comment by allancole** [comment]
I agreed that we should support taxonomy term descriptions. Once we have a PR for it, we can include it as a general improvement for a future update to the theme in the wporg themes repository.

**Comment by laurelfulford** [comment]
Closing this ticket, as it's been moved to Core Trac here: https://core.trac.wordpress.org/ticket/45911
