### ISSUE TITLE
style-rtl.css is a clone of style.css

### ISSUE THREAD

**Issue by DannyCooper** [WordPress/twentynineteen#257]
Usually the RTL stylesheet only includes the code required to overwrite the specific elements that display differently.

example: https://github.com/WordPress/twentyseventeen/blob/master/rtl.css

**Comment by grappler** [comment]
Not always. It may be performance wise be better just to load one file with all of the styles `style-rtl.css` instead of loading `style.css` and then the `style-rtl.css` to override the changes.

**Comment by DannyCooper** [comment]
Closing as @allancole explained:

“To clear this up a bit, the defaults themes have a separate RTL file but it only includes _overriding_ styles and has to be loaded in addition to `style.css` which isn’t always great for page load speed.

We could add all the RTL styles to the main `style.css` stylesheet but this also isn’t good for speed because were loading RTL styles when we don’t actually need them.

Right now it isn’t possible for the build tool to produce an RTL override like the `rtl.css` that appears in other default themes. Instead, when RTL is turned on, we’re replacing `style.css`  with `style-rtl.css` which is a duplicate of the main stylesheet but flipped for RTL support. Since `style-rtl.css` is generated automatically by the build tool, it stays consistent with any changes that happen in `style.scss`/`style.css`. And since we’re only loading this one file or the other (RTL or LTR), there’s no impact on page load speed in the end.”
