### ISSUE TITLE
Consider to remove the SVG icons ID attribute

### ISSUE THREAD

**Issue by afercia** [WordPress/twentynineteen#267]
Not sure if the `id` attribute output in the SVG icons markup is necessary for some reason. If not necessary, I'd like to suggest to remove it as it produces duplicate IDs in the same page (and invalid HTML).

For example, all the top level items in the main navigation menu have a `arrow_drop_down_circle` icon, so there are multiple `<svg id="ui-icon-arrow_drop_down_circle" ... ` in the page.

Same can happen with any SVG icon used more than once in the same page.

**Comment by kjellr** [comment]
Good catch. I don't think it's necessary either — I don't believe we use those IDs anywhere.

**Comment by kjellr** [comment]
Closed via #271
