### ISSUE TITLE
Links in the content don't have a focus style

### ISSUE THREAD

**Issue by afercia** [WordPress/twentynineteen#277]
As far as I see, links within the post content don't have any focus style. Indication of focus must always be clear and predictable for all users.

**Comment by 00travelgirl00** [comment]
Reladet PR #321

I could not find out how to style just the links in entry-content with sass.

**Comment by kjellr** [comment]
Fixed via #321. 

<img width="764" alt="screen shot 2018-10-26 at 10 52 35 am" src="https://user-images.githubusercontent.com/1202812/47574294-45951300-d90d-11e8-9f5b-c00c7e7c4fd5.png">
