### ISSUE TITLE
Hoefler Text font text underline on mac barely visible in Firefox and Safari

### ISSUE THREAD

**Issue by afercia** [WordPress/twentynineteen#278]
Fonts have internal metrics that may be rendered differently by different font rendering engines on different browsers and operating systems. On macOS, the actual font picked up from the font stack is "Hoefler Text".

Seems the text underline, which is of fundamental importance to distinguish links from normal text, is comfortably visible in Chrome and Opera but it's barely visible in Firefox and Safari. A quick comparison:

latest Chrome on macOS:

<img width="1023" alt="links chrome" src="https://user-images.githubusercontent.com/1682452/47447817-c396d400-d7be-11e8-817a-a2cc169bf66b.png">

latest Safari on macOS:

<img width="870" alt="links safari" src="https://user-images.githubusercontent.com/1682452/47447899-f04aeb80-d7be-11e8-898b-a7252dddcd55.png">

latest Firefox on macOS:

<img width="882" alt="links firefox" src="https://user-images.githubusercontent.com/1682452/47447911-f640cc80-d7be-11e8-9786-d81af24ed657.png">

As you can see, especially on Firefox the links are barely distinguishable from normal text (in absence of color). Worth considering the needs of users with vision impairments, even moderate ones, color perception impairments, or the elderly. The underline is so subtle that basically has no beneficial effect to distinguish a link.

On Windows 10, the actual font used seems to be "Baskerville Old Face" which seems to have a nice underline in all browsers I've tested with. Below, a screenshot of latest Firefox on WIn 10:

![firefox windows](https://user-images.githubusercontent.com/1682452/47448127-8b43c580-d7bf-11e8-9277-0103ea4ed42f.png)

I haven't tested on any *nix machine.

**Comment by kjellr** [comment]
Related to possible enhancements in #205.

**Comment by allancole** [comment]
Closing this issue since a working solution was merged in here: https://github.com/WordPress/twentynineteen/pull/186  

A more in-depth design discussion has been moved to Trac where we’ll be maintaining the code going forward. See here: https://core.trac.wordpress.org/ticket/45925
