### ISSUE TITLE
Allow users to turn off image filters

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#284]
The theme already includes a filter to turn off our featured image filters: 

https://github.com/WordPress/twentynineteen/blob/7eb93d5f79eedb168f72ccfeddbfcf6f0f129875/inc/template-functions.php#L120

We should make this a theme option, so it's available within the Customizer. If a user chooses to turn off image filters:

- Featured images within archive pages should have no overlay on them at all.
- Featured images on single post pages have text on top of them, so they should have an overlay. I suggest adding a layer of `black` at `0.7` opacity in that case:

### Screenshots, with filters disabled:

_In post feed, archive pages (no overlay):_

![screen shot 2018-10-24 at 4 22 47 pm](https://user-images.githubusercontent.com/1202812/47459070-31d09c00-d7a9-11e8-8d76-bb807eb8a1da.png)

_On single post pages (black overlay at `0.7` opacity):_

![screen shot 2018-10-24 at 4 15 13 pm](https://user-images.githubusercontent.com/1202812/47459107-46ad2f80-d7a9-11e8-903e-f376a20300d8.png)

**Comment by nielslange** [comment]
Closed as fixed when #327 will be merged.
