### ISSUE TITLE
Avatar is misaligned on comment form

### ISSUE THREAD

**Issue by remediosaraya** [WordPress/twentynineteen#289]
Issue:
The comment area avatar is misaligned. When we load the page for the first time, the first comment.
Screenshot:
<img width="904" alt="screen shot 2018-10-24 at 3 55 17 pm" src="https://user-images.githubusercontent.com/4819636/47464532-ba9a0880-d7a6-11e8-88af-24c0494ce6aa.png">
<img width="945" alt="screen shot 2018-10-24 at 3 55 07 pm" src="https://user-images.githubusercontent.com/4819636/47464533-bb329f00-d7a6-11e8-8efa-4150337cd9e3.png">

Solution:

Change css from position absolute to relative
```
#comments > #respond .comment-user-avatar {
    position: relative;
}
```

**Comment by remediosaraya** [comment]
hide the avatar like on the tablet and mobile version is a good fix too

**Comment by kjellr** [comment]
Thanks, @remediosaraya! There's actually already an issue filed for this in https://github.com/WordPress/twentynineteen/issues/213. We have a soon-to-land PR for the fix here: https://github.com/WordPress/twentynineteen/pull/214. I'm going to close this ticket for now, but the report is highly appreciated!
