### ISSUE TITLE
Support for non-latin font fallbacks

### ISSUE THREAD

**Issue by waviaei** [WordPress/twentynineteen#29]
Looking at the [_fonts.scss](https://github.com/WordPress/twentynineteen/blob/master/sass/variables-site/_fonts.scss), most of the specified fonts -- as I am aware -- only support Latin alphabets.  They do not support or only very limited support for non-latin alphabets.

In addition to that, serif fonts are specified as the primary body font. 

`$font__body: "Hoefler Text", "Baskerville Old Face", Garamond, "Times New Roman", serif;`

In Japanese, non-serif fonts are more commonly used on the web. If serif fonts are used, we need to consider the choice of them very carefully, else readability and aesthetics become absolutely terrible.

Are there any similar cases in any other languages? I am not sure.

The same issue regarding better support for non-latin font fallbacks was raised and applied in the development of twentyseventeen https://github.com/WordPress/twentyseventeen/issues/59

I would like to raise this issue for same matter to be considered in Twentynineteen too. 

---

_19-Oct Edit by designsimply_

List of alphabets supported in `twentyseventeen` that we also want to try support:

1. Cyrillic ( https://github.com/WordPress/twentyseventeen/pull/364 )
1. Greek ( https://github.com/WordPress/twentyseventeen/pull/366 )
1. Hebrew ( https://github.com/WordPress/twentyseventeen/pull/294 )
1. Arabic ( https://github.com/WordPress/twentyseventeen/pull/398 )
1. Vietnamese ( See [twentyseventeen/59 (comment)](https://github.com/WordPress/twentyseventeen/issues/59#issuecomment-254065128) and [twentyseventeen/59 (comment)](https://github.com/WordPress/twentyseventeen/issues/59#issuecomment-260561023) )
1. Thai ( https://github.com/WordPress/twentyseventeen/pull/93 )
1. Japanese ( https://github.com/WordPress/twentyseventeen/pull/155 )
1. Korean ( https://github.com/WordPress/twentyseventeen/pull/286 )
1. Chinese ( https://github.com/WordPress/twentyseventeen/pull/359 )
1. Devanagari ( https://github.com/WordPress/twentyseventeen/pull/403 )
1. Gujarati ( https://github.com/WordPress/twentyseventeen/pull/404 )

Checklist for `twentynineteen` PRs:

- [ ] Cyrillic (~#343~ #383)
- [ ] Greek (~#344~ #383)
- [ ] Hebrew (~#345~ #383)
- [ ] Arabic (~#346~ #383)
- [ ] Vietnamese (~#347~ #383)
- [ ] Thai (~#348~ #383)
- [ ] Japanese (~#341~ #383)
- [ ] Korean (~#349~ #383)
- [ ] Chinese (~#351~ #383)
- [ ] Devanagari (~#352~ #383)
- [ ] Gujarati (~#353~ #383)

**Comment by slaFFik** [comment]
Oh yes, Cyrillic please too!

**Comment by joyously** [comment]
We can solve it the same way we did in Twenty Seventeen, which is using the language attribute on the html tag to define a different set of fonts.

**Comment by philiparthurmoore** [comment]
Is this semi-finalized?

`"Hoefler Text", "Baskerville Old Face", Garamond, "Times New Roman", serif;`

If so then I'm happy to test Vietnamese.

**Comment by kjellr** [comment]
@philiparthurmoore: Go for it. 👍

**Comment by nielslange** [comment]
Language | ISO Codes | Fonts | Tester | PR
------------ | ------------- | ------------- | ------------- | -------------
Cyrillic | bg_BG, ru_RU, uk_UA | font_family: 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, sans_serif; | n/a | n/a
Greek | el_GR | font_family: 'Helvetica Neue', Helvetica, Arial, sans_serif; | n/a | n/a
Hebrew | he_IL | font_family: 'Arial Hebrew', Arial, sans_serif; | n/a | n/a
Arabic | ar_AE, ar_BH, ar_DZ, ar_EG, ar_IQ, ar_JO, ar_KW, ar_LB, ar_LY, ar_MA, ar_OM, ar_QA, ar_SA, ar_SY, ar_TN, ar_YE, fa_IR, ps_AR | font_family: Tahoma, Arial, sans_serif; | n/a | n/a
Vietnamese | vi-VN | font-family: 'Libre Franklin', sans-serif; | @philiparthurmoore | n/a
Thai | th_TH | font-family: 'Sukhumvit Set', 'Helvetica Neue', helvetica, arial, sans-serif; | n/a | n/a
Japanese | ja_JP | font_family: 'Hiragino Kaku Gothic Pro', Meiryo, sans_serif;  (Headlines) - font-family: 'Helvetica Neue', helvetica, arial, sans-serif; (Content) | n/a | n/a
Korean | ko_KR | font_family: 'Apple SD Gothic Neo', 'Malgun Gothic', 'Nanum Gothic', Dotum, sans_serif; | n/a | n/a
Chinese | zh_CN, zh_HK, zh_MO, zh_SG, zh_TW | font-family: 'PingFang TC', 'Helvetica Neue', Helvetica, STHeitiTC-Light, Arial, sans-serif; | n/a | n/a
Devanagari | bn_BD, hi_IN, mr_IN, ne_NP | font_family: Arial, sans_serif; | n/a | n/a
Gujarati | gu_IN | font_family: Arial, sans_serif; | n/a | n/a

👨‍💻 Implemention in progress ...

**Comment by nielslange** [comment]
> @nielslange Is there a reason why we want to load a seperate CSS file for each language instead of doing it how it was done in Twenty Seventeen? https://github.com/WordPress/twentyseventeen/blob/master/style.css#L584

@grappler I decided to outsource the language support to avoid that all additional languages get loaded all the time. I don't see any benefits in loading Cyrillic, Greek, Hebrew, etc. when the site language is set to English. Given the fact that on language CSS file has 80+ lines of code, we would load 900+ extra lines of code, that are not necessary for languages with a Latin character set. What issues do you see in outsourcing these separate files?

**Comment by kjellr** [comment]
Thanks @nielslange for getting all these PRs up and running. Just noting that I've updated the main issue above to include links to each PR: That way we can use this thread to keep track of which ones have been tested, approved, and merged.

**Comment by philiparthurmoore** [comment]
@nielslange Thanks a ton - I'll take care of that on Saturday.

**Comment by joyously** [comment]
You do know that you can get the user's installed font by using `serif` or `sans-serif` or `monotype`, right? There isn't a need to specify specific fonts if you are going for a generic look, and the user would get whatever font they chose in their browser. Big impact with very little CSS.

**Comment by allancole** [comment]
The proposed solution for the is very thorough, which is great but I think @joyously’s suggestion might be ideal here. I’m worried that adding so many additional language-specific font-styles would be really difficult to maintain and keep in-sync with the theme’s selectors. Twenty Seventeen only had one font, so there’s far fewer selectors to consider compared to Twenty Nineteen, where we have 2 fonts that get switched back and forth depending on context. 

As suggested, if we rely on the browser’s font setting for non-en languages, then something like this would be more simple and wouldn’t add nearly as much CSS _weight_ if it were included in `style.css` directly: 

```
/* if language doesn’t start with en- (any site thats _not_ in english) */
html:not([lang^="en-"]) * {
  font-family: sans-serif;
}
```

If that’s too aggressive, we could also go with something more specific that still skips over the theme’s selectors. This would still cut down on the number of selectors needed to support languages for fonts and it’d be small enough to include in the main stylesheet too:

```
/* Arabic */
html[lang="fa-IR"] *,
html[lang="ur"] * {
  font-family: Tahoma, Arial, sans-serif;
}

/* Korean */
html[lang="ko_KR"] * {
  font-family: "Apple SD Gothic Neo", "Malgun Gothic", "Nanum Gothic", Dotum, sans_serif;
}
```

Curious what your thoughts are on this @philiparthurmoore & @nielslange. I tried both snippets in my Chrome/Mac os browser but not sure how well it would work everywhere in real-world scenarios.

**Comment by philiparthurmoore** [comment]
@allancole I'd be more in favor of a `sans-serif` and `serif` only approach for the reasons both you and @joyously have outlined. Maintainability is worth avoiding over-engineering this. That said, you're the designer. If keeping it too simple means compromising on an already minimal design then I'd probably be okay with the more involved approach.

**Comment by nielslange** [comment]
@allancole In general I like the idea of unsins less code to keep the language support maintainable. Your code snippets above will not work due to CSS Specificity. Having said that, if you add `!important` to your statements it should work. I’m not a fan of using `!important` in general, but in favor of keeping the CSS code short, I’m happy to use it. 😉

I’m on the road currently, but will adjust the code later today.

**Comment by mayukojpn** [comment]
Hi @nielslange ! If it enqueues css separately, I suggest renaming the folder to `css` like what `js` does. Or, you might need to add `s` to make it `languages` - it was .pot location of default themes older than [Twenty Sixteen](https://themes.trac.wordpress.org/browser/twentysixteen/1.0).

**Comment by waviaei** [comment]
Hi! Sorry, I just couldn't find a time to follow up after submitting the issue. Huge thanks in recognizing and considering this issue, and great to see this moving forward.

**Comment by nielslange** [comment]
I've closed all single language support PRs in favour of #383. 

@slaFFik Feel free to test the Cyrillic implementation.
@philiparthurmoore Feel free to test the Vietnamese implementation.
@mirucon Would you mind testing the Japanese implementation?
