### ISSUE TITLE
Some small things noted during translation

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/twentynineteen#291]
https://build.trac.wordpress.org/browser/branches/5.0/wp-content/themes/twentynineteen/inc/template-tags.php Line 43 contains a translators comment that doesn't make sense in the current context:

`/* translators: 1: SVG icon. 2: post author, only visible to screen readers. 3: author link. */ `

There's another one in line 83:

`/* translators: 1: SVG icon. 2: posted in label, only visible to screen readers. 3: list of categories. */`

Further:
https://build.trac.wordpress.org/browser/branches/5.0/wp-content/themes/twentynineteen/single.php Line 29

A space character is missing between "in" and the post title. 
`'prev_text' => _x( '<span class="meta-nav">Published in</span><span class="post-title">%title</span>', 'Parent post link', 'twentynineteen' ),`

WP-org username: tobifjellner (i.e. same as here...)

**Comment by grappler** [comment]
I think the PR https://github.com/WordPress/twentynineteen/pull/237 should fix some of those.

**Comment by dimadin** [comment]
Also see #217.

**Comment by kjellr** [comment]
Closing this since both of the referenced PRs (#237 and #217) have been merged in. 👍
