### ISSUE TITLE
Unable to click into single posts that have no title.

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#297]
To test:
- Create a post, do not give it a title
- View it in the feed.

There's currently no way to click into the full post view. We should add the post date to the post meta at the bottom, linking to the post's permalink. 

_Screenshot_
<img width="693" alt="screen shot 2018-10-24 at 9 51 17 pm" src="https://user-images.githubusercontent.com/1202812/47471170-2005ed80-d7d7-11e8-96c4-15f1f7e04d36.png">

**Comment by nielslange** [comment]
@kjellr What about adding the `Continue reading` button below the post in such a case? Happy to create a PR later today.

**Comment by kjellr** [comment]
In this case, there may not actually be any more to read. 😄 I think just adding a post date section to  the meta makes sense — we already  =display one at the top of the single post page: 

<img width="645" alt="screen shot 2018-10-24 at 10 15 49 pm" src="https://user-images.githubusercontent.com/1202812/47471914-90fad480-d7da-11e8-9229-e04ef19f52d6.png">

**Comment by nielslange** [comment]
@kjellr Isn't that too cryptic? Personally, I would not expect that clicking on the post date will lead to the single post view. 🤔

Concerning the `Continue reading` I would slightly disagree, as there might be comments to read. Let me take a look at how other Twenty themes behave in this case.

**Comment by carolinan** [comment]
I think clicking the post date to reach a single post is a very common pattern,  but less common in the footer below the post.

**Comment by allancole** [comment]
This is technically an edge case, so as long as there is _some_ way to get to the singular view, I think we’ll be okay. 

A `Continue reading` link is usually something we want users to add, so I don’t think its right for the theme to introduce something that the user can’t remove or didn’t opt into.

On the singular view, there’s an `.entry-meta` that site below the post-title and above the post-content. Maybe we could show that when there’s no title?

**Comment by nielslange** [comment]
I've created #297 to fix this issue. To avoid crucial design changes I've only added the post date to the footer.
