### ISSUE TITLE
Fix post password field size/spacing issues.

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#298]
Currently, the post password field is very large compared to the button next to it:

<img width="535" alt="screen shot 2018-10-24 at 10 00 48 pm" src="https://user-images.githubusercontent.com/1202812/47471477-69a30800-d7d8-11e8-8e94-e7f8e55774eb.png">

It should be the same height as the button, and should have a little extra space to the right and left:  

![password-field](https://user-images.githubusercontent.com/1202812/47471573-e33af600-d7d8-11e8-85ee-1694603e5ef8.png)

**Comment by briannaorg** [comment]
Made some adjustments to the global input and button styles to match up vertically.

<img width="713" alt="screen shot 2018-10-24 at 10 35 03 pm" src="https://user-images.githubusercontent.com/3371846/47474837-922e0080-d7de-11e8-9f20-fbfa1a15b9fa.png">

**Comment by kjellr** [comment]
Fixed via #304
