### ISSUE TITLE
Style pingbacks

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#299]
Currently pingbacks are completely unstyled. These should have some sort of treatment. 

<img width="716" alt="screen shot 2018-10-24 at 10 03 12 pm" src="https://user-images.githubusercontent.com/1202812/47471590-f221a880-d7d8-11e8-8da1-b9d853deef27.png">

**Comment by nielslange** [comment]
@melchoyce Would you mind taking a look at the pingback styling options? These are the pingback styles of the other Twenty themes. On the other hand, the pingbacks look quite nice in the Twenty Nineteen theme. Thus, I wonder if we should even style them or just keep them as they are. 🤔

CC: @kjellr 

## Twenty Seventeen
<table>
<tr>
<td valign="top">iPad:

![299 - twenty seventeen ipad](https://user-images.githubusercontent.com/3323310/47507603-a801fb00-d89c-11e8-9b4f-cdc77319ebae.png)</td>
<td valign="top">iPhone X:

![299 - twenty seventeen iphone x](https://user-images.githubusercontent.com/3323310/47507602-a7696480-d89c-11e8-8bb8-5a4d79e7d3b4.png)</td>
</tr>
</table>

## Twenty Sixteen
<table>
<tr>
<td valign="top">iPad:

![299 - twenty sixteen ipad](https://user-images.githubusercontent.com/3323310/47509187-c87f8480-d89f-11e8-972e-7f2611a8887d.png)</td>
<td valign="top">iPhone X:

![299 - twenty sixteen iphone x](https://user-images.githubusercontent.com/3323310/47509190-c87f8480-d89f-11e8-9bc7-aa416af2014e.png)</td>
</tr>
</table>

## Twenty Fifteen
<table>
<tr>
<td valign="top">iPad:

![299 - twenty fifteen ipad](https://user-images.githubusercontent.com/3323310/47507872-3b3b3080-d89d-11e8-969d-76310a18860e.png)</td>
<td valign="top">iPhone X:

![299 - twenty fifteen iphone x](https://user-images.githubusercontent.com/3323310/47507880-3e362100-d89d-11e8-90d6-578c250a5750.png)</td>
</tr>
</table>

## Twenty Fourteen
<table>
<tr>
<td valign="top">iPad:

![299 - twenty fourteen ipad](https://user-images.githubusercontent.com/3323310/47508416-480c5400-d89e-11e8-8c8e-e4eee1f5e8e4.png)</td>
<td valign="top">iPhone X:

![299 - twenty fourteen iphone x](https://user-images.githubusercontent.com/3323310/47508362-2d39df80-d89e-11e8-8898-7db2c95153ff.png)</td>
</tr>
</table>

## Twenty Thirteen
<table>
<tr>
<td valign="top">iPad:

![299 - twenty thirteen ipad](https://user-images.githubusercontent.com/3323310/47508572-8dc91c80-d89e-11e8-80bc-22d6dc98d9ab.png)</td>
<td valign="top">iPhone X:

![299 - twenty thirteen iphone x](https://user-images.githubusercontent.com/3323310/47508570-8d308600-d89e-11e8-9302-a2979dc2195a.png)</td>
</tr>
</table>

## Twenty Twelve
<table>
<tr>
<td valign="top">iPad:

![299 - twenty twelve ipad](https://user-images.githubusercontent.com/3323310/47508949-42633e00-d89f-11e8-97e3-d7ca7696e1a2.png)</td>
<td valign="top">iPhone X:

![299 - twenty twelve iphone x](https://user-images.githubusercontent.com/3323310/47508951-42fbd480-d89f-11e8-8bf4-cb5f3e15f70b.png)</td>
</tr>
</table>

## Twenty Eleven
<table>
<tr>
<td valign="top">iPad:

![299 - twenty eleven iphone x](https://user-images.githubusercontent.com/3323310/47509012-5e66df80-d89f-11e8-8b32-b83435869311.png)</td>
<td valign="top">iPhone X:

![299 - twenty eleven ipad](https://user-images.githubusercontent.com/3323310/47509018-5eff7600-d89f-11e8-8d6b-97e2243b573d.png)</td>
</tr>
</table>

**Comment by kjellr** [comment]
@nielslange let's do something like this:  

<img width="714" alt="screen shot 2018-10-25 at 11 07 04 am" src="https://user-images.githubusercontent.com/1202812/47510578-6cd4dd00-d846-11e8-90b7-78679c5ad914.png">

**Comment by nielslange** [comment]
@kjellr Why is that pingback placed between the comments? Is that intended or did that happen by accident? If not, what's the logic behind it? Shall both comments and pingbacks be listed descending by date?

**Comment by kjellr** [comment]
Sorry — I was messing around with something else at the time. I  don't meant to adjust the placement or order of comments/pingbacks. Let's just style the pingback alignment, label, and title as shown there.

**Comment by nielslange** [comment]
@kjellr Thanks for clarifying this. On #336 you can now find and review my PR.
