### ISSUE TITLE
Add padding between prev/next post navigation

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#300]
Previous/Next Post navigation titles can run into each other if they're long enough. When these two links are stacked side by side like this, we should add padding to make sure this doesn't happen: 

<img width="825" alt="screen shot 2018-10-24 at 10 10 05 pm" src="https://user-images.githubusercontent.com/1202812/47471747-c521c580-d7d9-11e8-894e-01f527cc2a89.png">

**Comment by briannaorg** [comment]
Added 1rem of padding at desktop sizes. 

<img width="912" alt="screen shot 2018-10-24 at 10 16 59 pm" src="https://user-images.githubusercontent.com/3371846/47474062-f8188900-d7da-11e8-9392-223448fe7dfb.png">

**Comment by allancole** [comment]
Fixed in #303
