### ISSUE TITLE
Remove Comma after last element of menu item

### ISSUE THREAD

**Issue by monika-12** [WordPress/twentynineteen#306]
There is no need to add comma after last item of menu item.
![twenty-nineteen](https://user-images.githubusercontent.com/17018981/47477827-c3d9b280-d844-11e8-8572-f463c5806769.jpg)

**Comment by nielslange** [comment]
@monika-12 This issue should have been fixed with #263. Is it possible that you're not using the latest version?

**Comment by monika-12** [comment]
@nielslange  I am using WP beta version. 
Should I need to do anything else ?

**Comment by nielslange** [comment]
@monika-12 Thanks for clarifying that. WordPress 5.0 beta 1 does not contain the latest changes of this repo. #263 had been merged 16 hours ago, and thus after the beta version got released. You could download the latest Twenty Nineteen theme directly via https://github.com/WordPress/twentynineteen as seen on

![annotation on 2018-9-4](https://user-images.githubusercontent.com/3323310/47479552-b843b700-d857-11e8-947a-e01d1438544b.png)

However, this version will change every few hours as we're working hard on this version. Are you familiar with Git? Then you could check out the latest version though. 😉

**Comment by nielslange** [comment]
Great. Happy to hear that, @monika-12. Also, feel free to close this issue once you can confirm that the comma behind the last element is no longer visible.
