### ISSUE TITLE
Document Sass compilation, editor style syncing

### ISSUE THREAD

**Issue by nickcernis** [WordPress/twentynineteen#31]
How should we document how Sass is expected to be compiled? I'm for it, but its inclusion scared some folks in the #core-themes chat today. Some education about how to work with it might reduce any fears.

The [announcement post](https://make.wordpress.org/core/2018/10/16/introducing-twenty-nineteen/) also mentions:

> SASS is used in some key areas which has been helpful for keeping styles in-sync between the Gutenberg editor, and the front-end experience.

Please could this process also be documented or described briefly? (For example, how should those using Twenty Nineteen as a starter theme write custom block styling and keep editor styles in-sync?)

**Comment by nielslange** [comment]
@nickcernis I assume this issue can be closed now that #169 got merged, correct?

**Comment by nickcernis** [comment]
@nielslange Yes, that looks good — closing. Thanks for checking in!
