### ISSUE TITLE
Remove Comma in site info if site title is not there

### ISSUE THREAD

**Issue by monika-12** [WordPress/twentynineteen#312]
There is comma displaying before "Proudly powered by WordPress" text if site title is not there. 
![screenshot-wp local-2018 10 25-17-25-21](https://user-images.githubusercontent.com/17018981/47498467-fd2d1500-d87a-11e8-8cee-6742048487c5.png)

**Comment by nielslange** [comment]
Thanks for reporting this issue, @monika-12! I just created a fix for this issue in #314.
