### ISSUE TITLE
attachment page problems

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#323]
This is an attachment page. There is a `--Published inPost Format: Gallery` text that
1) is misaligned, 
2) it didn't let me select the gray part, 
3) the gray part is showing the link cursor, 
4) there is no space between the label and the link.
Also, the caption of the image is not shown on the page.

![attachment-page](https://user-images.githubusercontent.com/7957680/47516675-b247d900-d84b-11e8-88e6-8ab26894dd5f.jpg)

**Comment by pattonwebz** [comment]
I think I can see why these issues are happening, I did be able to submit a PR with fixes by end of day.
