### ISSUE TITLE
SVG icons have two width and height attributes

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#329]
This is from the menu:

`<svg class="svg-icon" width="16" height="16" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 12l-4-4h8l-4 4z"/></svg>`

**Comment by joyously** [comment]
Should be in RC1 milestone.

**Comment by kjellr** [comment]
This one should've been closed actually — #333 took care of it. 👍
