### ISSUE TITLE
Comma separated menu items may not work in all languages

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentynineteen#33]
I noticed that the mock-ups show a comma separated menu. This was brought up in a comment on the make blog that it may not work very well in all languages. https://make.wordpress.org/core/2018/10/16/introducing-twenty-nineteen/#comment-34162 This should probably be discussed to see if the menu should use commas or not.

**Comment by mindctrl** [comment]
Related: https://github.com/WordPress/twentynineteen/issues/32

**Comment by ihorvorotnov** [comment]
Related: #1 (in some languages, average word length is way bigger than in English).

**Comment by joyously** [comment]
I had to try to figure out what those comma separated words were. Are they a menu? It is so hard to tell. It looks like part of the site description. 
This menu definitely needs a better look.

**Comment by kjellr** [comment]
Closing this via #263, which removes the commas.
