### ISSUE TITLE
Background color is not set for classic editor

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#331]
I set the background color to light green and edit a post in classic editor. The background color is white there.

**Comment by monika-12** [comment]
@joyously 

Can you please explain the steps to reproduce the bug ?

**Comment by joyously** [comment]
I used Customizer to set the background color to light green.
I clicked Save and Publish.
I chose a post to edit.
Using Visual mode, the theme styles for headings and fonts are there, but the background color is white.

**Comment by joyously** [comment]
So, with the change to the Customizer, the background color is no longer an option. If it is staying this way, close this issue.

**Comment by kjellr** [comment]
> So, with the change to the Customizer, the background color is no longer an option. If it is staying this way, close this issue.

That's correct, so we can close this for now. Thanks!
