### ISSUE TITLE
If Sass: Create unified build process for development

### ISSUE THREAD

**Issue by mor10** [WordPress/twentynineteen#34]
If Sass is chosen as the CSS modality, a unified build process should be included in the theme repo to ensure:
 
1. every contributor works with the same settings
2. Sass doesn't become a barrier to entry

The build process should include Sass processing (ideally through PostCSS), and probably enforce the WordPress style guide through Stylelint.

I vote for a Gulp process since it is relatively easy to understand and manage.

**Comment by tarikhamilton** [comment]
I vote for webpack. WordPress uses it, vue-cli uses it, and create-react-app uses it. 

WordPress developers need to be exposed to modern tooling and learning what a webpack config looks like and how it works may serve them more in the future than Gulp.

**Comment by mor10** [comment]
WebPack is excellent for JavaScript-heavy projects that require dedicated JS management. That's not the case here. The smallest and easiset solution is the best. It might be as simple as npm scripts with no build tool. If a build tool is needed, Gulp makes more sense for this type of project because it just uses straight up JavaScript. WebPack introfuces an unnecessary level of complexity for something pretty straight forward. In my opinion.

**Comment by spencerfinnell** [comment]
If SCSS/Sass is the only build dependency I would really like to see it just run as a standard `npm` command vs. using Gulp.

**Comment by mor10** [comment]
Im fine with that. We should also wire in Stylelint to adhere to WordPress Coding Standards.

**Comment by ntwb** [comment]
There's a [PR in the Underscores repo](https://github.com/Automattic/_s/pull/1159), we should get updated, merged, then pulled into this repo....

**Comment by dingo-d** [comment]
I'm more for webpack, since it's already used in core to bundle JS files [ref](https://core.trac.wordpress.org/ticket/40894)

**Comment by nielslange** [comment]
@mor10 I assume this issue can be closed now that #169 got merged, correct?
