### ISSUE TITLE
Apply white Box Shadow on Site Logo Hover when Background image is applied

### ISSUE THREAD

**Issue by monika-12** [WordPress/twentynineteen#340]
When Background image is applied from Customizer Black box shadow on Logo Hover will not work so it should be white box shadow there.

![black-shadow](https://user-images.githubusercontent.com/17018981/47548123-97da3200-d915-11e8-921c-bd23d82b526d.jpg)

**Comment by zengxiaoluan** [comment]
hello，这个主题有什么特色呢？设计风格有什么不同？

**Comment by kjellr** [comment]
@monika-12 — there appears to be some other errors going on in this screenshot too... the blue menu text, the black text, etc. Under what circumstances did you see this?

Thanks!

**Comment by allancole** [comment]
Closing this since it’s been fixed on another PR.
