### ISSUE TITLE
Include one CSS Custom Property in shipped code to move the web forward

### ISSUE THREAD

**Issue by mor10** [WordPress/twentynineteen#35]
CSS Custom Properties (ie "variables") need more presence on the web for the browser manufacturers to fast-track the feature. By adding a single custom property in the shipped code of Twenty Nineteen, we will increase the frequency of use of this feature by millions of sites, thus helping to move the web forward.

It would be easy to include a single custom property with appropriate fallbacks in the theme to provide backwards compatibility. The total impact would be ~4 lines of CSS and would have no impact on the end-user.

**Comment by joyously** [comment]
We should use more than one! 
I suggested this in #core-editor. It would be so easy to do editor styles if they were Custom Properties.
I used a polyfill for older browsers, but I used them extensively in a theme I wrote this past year.

**Comment by joyously** [comment]
@mor10 Can you think of a way to use one? Since we still have to support IE11, it's difficult without a polyfill, but what if there were a progressive enhancement, such as background-blend-mode or something for modern browsers? If we use a variable there, we don't have to worry about IE11.

**Comment by joyously** [comment]
@mor10 
Can you put a variable in for the featured image `mix-blend-mode`? There is already alternate support for the old browsers, so that's a case where there would be only modern browsers using it.

**Comment by mor10** [comment]
We don't need to put an actual functional variable in the code. It could just be a color that falls back on a hard-coded color:

```css
:root {
  --key-color: #4169E1;
}

.entry-title {
  color: #4169E1 /* fallback for older browsers */
  color: var(--key-color);
}
```

Of course this could (and probably should) be expanded to handle color schemes if this theme ships with them, but that's a lot more complex. Starting small still makes a huge difference.

**Comment by kjellr** [comment]
I don't believe this ended up happening for launch, due the compressed timeline and other priorities. I'm going to close this issue rather than migrate it over to Trac, as it's not quite actionable at this stage. If anyone has ideas for using one of the custom properties mentioned moving forward, feel free to open up a Trac ticket for discussion.

Thank you!
