### ISSUE TITLE
Optimize font styling

### ISSUE THREAD

**Issue by grappler** [WordPress/twentynineteen#350]
While looking at #344 I saw there were multiple classes being used to define the header font styles.

This caused me to look at the default styles. For the heading styles we have loads of classes that have a custom header font. This does not seem very clean and organised.

https://github.com/WordPress/twentynineteen/blob/b5a501938014f2cbb709e2b1e6bfd41ab68386c8/sass/typography/_headings.scss#L1-L20

I am not a CSS expert but I feel we can optimise the CSS. For example do we need `h2.author-title` and `h2` or `.error-404 .page-title` and `.not-found .page-title` where `.page-title` may suffice.

The font family is being defined twice for `.page-description`.

It should be nearly possible to just have.
```
h1, h2, h3, h4, h5, h6 {
	font-family: $font__heading;
}
```

**Comment by joyously** [comment]
Or, like in Twenty Seventeen,
`html[lang="ar"] { 
    font-family: 'Arabic font', sans-serif;
}
html[lang="gr"] { 
    font-family: 'Greek font', sans-serif;
}`

**Comment by grappler** [comment]
@joyously I mean in  a general sense and not language specific.

**Comment by joyously** [comment]
I know, but why not? We did that in Twenty Seventeen.

**Comment by grappler** [comment]
> I know, but why not? We did that in Twenty Seventeen.

The disucssion for that should be done in https://github.com/WordPress/twentynineteen/issues/29

The point of this issue is reduce the number of classes used to define header fonts.
