### ISSUE TITLE
Theme with BuddyPress Profile view is not intuitive.

### ISSUE THREAD

**Issue by pooja-muchandikar** [WordPress/twentynineteen#355]
Refer the snapshot.

Using BuddyPress Plugin, and Twenty nineteen theme - profile page with twenty nineteen theme is not intuitive.

1. Profile icon looks so small. And name and profile are not aligned.
2. User active status is not aligned.
3. On cover image there is one horizontal line present, which shouldn't be. 

Check the snapshot. 

![profile1](https://user-images.githubusercontent.com/41000648/47567918-582f3c80-d94d-11e8-960e-9f66c21d8473.png)

**Comment by allancole** [comment]
Hi @pooja-muchandikar 👋 Thanks for contributing! We don’t typically provide compatibility support for specific plugins, unfortunately. 

We won’t be including BuddyPress compatibility in Twenty Nineteen, but here’s some information on how you might be able to add compatibility yourself: https://codex.buddypress.org/themes/theme-compatibility-1-7/a-quick-look-at-1-7-theme-compatibility/
