### ISSUE TITLE
Implement stylelint for CSS coding standard automation

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentynineteen#371]
https://stylelint.io/user-guide/cli/

We need to automate coding standard tests for CSS (ideally for SASS). We need stylelint for that. How would be implement this?

**Comment by anevins12** [comment]
Blocks #356

**Comment by atanas-angelov-dev** [comment]
My proposed PR: #419

**Comment by laurelfulford** [comment]
The Core version of Twenty Nineteen doesn't include the `travis.yml` file; since we're closing out this repo to move the theme development fully to the Core Trac, I'm going to close this issue. Thanks!
