### ISSUE TITLE
dropdown menu sometimes disappears

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#378]
When I hover over a menu item with a submenu, the submenu displays. But it often disappears before I can get my cursor onto it.

This is in Firefox 62 on Ubuntu.
![inconsistent-menu-2018-10-28 13-48](https://user-images.githubusercontent.com/7957680/47620484-8c733c00-dab8-11e8-8b48-00166288c755.gif)

**Comment by kjellr** [comment]
May be addressed as part of #337.

**Comment by allancole** [comment]
Fixed in #337
