### ISSUE TITLE
submenu jumps when clicked

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#379]
When I click on a submenu item, the entire submenu jumps to the left.

This is on Firefox 62 on Ubuntu.
![submenu-jump-2018-10-28 13-56](https://user-images.githubusercontent.com/7957680/47620577-8a5dad00-dab9-11e8-8c6a-d40c5f116d2a.gif)

**Comment by kjellr** [comment]
May be addressed as part of #337.

**Comment by allancole** [comment]
Fixed in #337
