### ISSUE TITLE
menu z-index problem

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#382]
On a window that is narrow enough to have the featured image smaller, so the post title is up by the menu, the submenu is "behind" the post title.

![menu-z-index-2018-10-28_15-26-19](https://user-images.githubusercontent.com/7957680/47621471-70769700-dac6-11e8-863d-fc8e61c32faa.jpg)

**Comment by kjellr** [comment]
Addressed in #337.

**Comment by allancole** [comment]
Fixed in #337
