### ISSUE TITLE
Sub-menu - display is not intuitive.

### ISSUE THREAD

**Issue by pooja-muchandikar** [WordPress/twentynineteen#386]
- Added sub-menu for the menu.

- Sub-menu is not displayed right below the parent menu.

- Also, the drop-down structure consists of more space in the sub-menu, after the menu-title.

Refer snapshot.

![child-menu](https://user-images.githubusercontent.com/41000648/47635884-7b8bfe80-db7c-11e8-86a4-4cc67830fa54.jpeg)

There should be an arrow pointing to parent-menu atleast.

**Comment by kjellr** [comment]
Thanks, @pooja-muchandikar. The menu is being reworked as part of #337 — this may be taken care of as part of that PR.

**Comment by allancole** [comment]
Closing this as the menu UI has been refactored and sub-menus are now more clearly display with their parent.
