### ISSUE TITLE
Cover Image aligncenter is not centered

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentynineteen#390]
In one of the recent commits, something has happened to the Cover Image when ```.aligncenter``` is selected. The alignment is not centered, nor does it match the backend anymore. See screenshots below

Before - last week
![centered-cover-image-chrome](https://user-images.githubusercontent.com/34601694/47674356-7be0c580-db8d-11e8-98e2-532242a0cbf0.PNG)

Now - today
![centered-cover-image-chrome-now](https://user-images.githubusercontent.com/34601694/47674305-5fdd2400-db8d-11e8-8f18-e1db43ae1a90.PNG)

Backend
![centered-cover-image-chrome-now-backend](https://user-images.githubusercontent.com/34601694/47674449-b185ae80-db8d-11e8-8e21-95983c192156.PNG)

**Comment by joyously** [comment]
I'm still seeing it uncentered.

![center-cover-image](https://user-images.githubusercontent.com/7957680/48103528-2c397400-e1f5-11e8-80b1-19a673abcc95.jpg)

**Comment by kjellr** [comment]
@joyously can you share what browser + version you're using? And is that in Gutenberg or on the front end?

I'm seeing these centered in my testing (FF 63.0.1, on MacOS 10.14):

<img width="1261" alt="screen shot 2018-11-06 at 9 43 15 pm" src="https://user-images.githubusercontent.com/1202812/48107292-13d55380-e20d-11e8-9333-bde64cdba49b.png">
<img width="1260" alt="screen shot 2018-11-06 at 9 43 02 pm" src="https://user-images.githubusercontent.com/1202812/48107293-13d55380-e20d-11e8-9909-98a2b7cdd2eb.png">
