### ISSUE TITLE
menu on small window, hovered 

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#394]
On a narrow window, the menu is still responding partially to hover. This includes color, but also some submenus, but the submenu text is not shown until the arrow is clicked. And once the arrow is clicked, it stays the hover color. I suppose this is okay, but odd.

![peek 2018-10-29 19-47](https://user-images.githubusercontent.com/7957680/47688573-0cca9780-dbb4-11e8-8c55-e64a1d8621d4.gif)

**Comment by kjellr** [comment]
Agreed — the menu on small screen still definitely needs some reworking. It's not yet in a fully workable state.
