### ISSUE TITLE
Menu subitems can extend offscreen on desktop

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#398]
Menu items can extend beyond the right side of the viewport. This happens especially frequently with submenu items.

![menu](https://user-images.githubusercontent.com/1202812/47690972-a7cc6d00-dbc6-11e8-82a7-a68bee378fd2.gif)

**Comment by joyously** [comment]
What happened to the menu showing only the items that fit? (I know that doesn't apply to submenu.) 
If you make your window smaller, the menu is wrapping around instead of having a `...` like it was proposed.

**Comment by kjellr** [comment]
> What happened to the menu showing only the items that fit?

That's still the plan, and is  an open PR (#268). It needs to be reworked a little so that it can be implemented alongside the menu updates that were pushed today.

**Comment by shahjehanali1** [comment]
@kjellr I've fixed this issue https://www.useloom.com/share/e368a9591e3644cea0dd82df45a7bd17

 but not b able to push code me in 'add/priority-menu-two'

**Comment by shahjehanali1** [comment]
https://gist.github.com/shahjehanali1/c8251b55b4fabc97edcf5f698958034b

**Comment by kjellr** [comment]
This should be generally taken care of via the updates in #485:

- Submenu items within dropdown menus are now exposed by default. We no longer use submenus that expand off to the right. 
- The Priority+ navigation button eats up top-level menu items that would otherwise cause overflow.

Those updates should handle the vast majority of potential problems here, so I'm going to close this issue for now. Please submit new issues if any other additional menu overflow problems are discovered.
