### ISSUE TITLE
Header image cropping: Need focal point control

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentynineteen#4]
Learning from the 2017 theme, we saw that people used the header image as more than just a decorative image. They cared about what was inside it and did not want it to be cropped arbitrarily as per the design requirements.

Some people use header images with text inside of the image. That's not great and that's not the use case that I'm focusing on. I'm focusing on people who have decorative images that also require focal control.

Recommendation: Can we add focal control in the dashboard?

**Comment by joyously** [comment]
That is sort of out of scope of a theme. There are plugins that provide it, though.

**Comment by kjellr** [comment]
I agree with @joyously here — while this would be useful, it unfortunately isn't something that makes sense to incorporate into a single theme for now.

The good news is that it's absolutely possible for this to be worked into Gutenberg (I know of at least one block author who's pursuing it). So a focal point picker could very likely be incorporated into phase two of Gutenberg, when it's able to expand outside of the editor itself. 

I'm going to close for now, but feel free to keep discussing if you have other related concerns.
