### ISSUE TITLE
Twenty Nineteen: Undefined twentynineteen_l10n variable in functions.php

### ISSUE THREAD

**Issue by mukeshpanchal27** [WordPress/twentynineteen#403]
WordPress shows below error when we check front end of Twenty Nineteen

Notice: Undefined variable: twentynineteen_l10n in /wordpress/wp-content/themes/twentynineteen/functions.php on line 167

**Comment by mukeshpanchal27** [comment]
![error](https://user-images.githubusercontent.com/10103365/47701322-6fb54080-dc3f-11e8-91f2-8d1309531d1a.png)

**Comment by allancole** [comment]
Ahh, good catch. I think something must’ve happened while merging that through this off. Thanks for contributing ;-)
