### ISSUE TITLE
Support for WP version

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentynineteen#431]
I did some testing with the theme in previous versions of WordPress.

I started with 4.6.12.
- the theme was **not compatible**, at least due to the use of the function `get_theme_file_uri()`. This function was indeed [introduced in 4.7](https://developer.wordpress.org/reference/functions/get_theme_file_uri/#changelog).
- in addition to this, I think that the Customizer hue control used for selecting the custom primary color isn't compatible with lower versions of WordPress either. The hue control was introduced for the default theme Twenty Seventeen.

I checked with version 4.7.11 as well as 4.8.6 and these versions seemed to work fine.

I suggest to add a version check in the `functions.php` file, as it was done for Twenty Seventeen. I suggest that we set 4.7+.
To be able to take advantage of the privacy policy functions, we would need 4.9.6+. However, since [we check whether the required function exists](https://github.com/WordPress/twentynineteen/blob/fd796f6e8dfa2d23ca2bd1f737dbb53ba7db14f0/footer.php#L28), we don't break anything between 4.7 and 4.9.6.

Another consideration could be whether 5.0 should be the first supported version since the theme is meant to showcase Gutenberg. Although guess that users on earlier versions could try Gutenberg as well using the plugin.

**Comment by joyously** [comment]
This was already mentioned in #207 and in the comments for #72.
Only the readme was updated.

**Comment by LittleBigThing** [comment]
Ok, missed the outcome of that discussion, sorry.
But I do think that #432 would be a gentle solution to avoid ugly errors being generated < 4.7.

**Comment by joyously** [comment]
I agree that it is probably needed. I was just providing references.

**Comment by kjellr** [comment]
Closing since #432 was merged. 👍
