### ISSUE TITLE
Using Columns In Editor Requires Horizontal Scrolling

### ISSUE THREAD

**Issue by billrobbins** [WordPress/twentynineteen#433]
When adding a column block to the editor, the second column displays too far to the right.  It requires scrolling to see.  Even when the editor is the full width of my iMac, it still will not fit in the available space.

![2019 Page In Editor](https://justabill.blog/wp-content/uploads/2018/10/2019-editor-columns.png)
Shot of TwentyNineteen theme with columns in editor.

---

![2017 Page In Editor](https://justabill.blog/wp-content/uploads/2018/10/2017-columns.png)
Shot of same page in TwentySeventeen theme.

**Comment by ianbelanger79** [comment]
I can confirm this issue, see screenshots

Twentyseventeen
![2017-columns](https://user-images.githubusercontent.com/34601694/47796492-d51a3780-dcfa-11e8-845d-20a4bc83c940.PNG)

Twentynineteen
![2019-columns](https://user-images.githubusercontent.com/34601694/47796504-db101880-dcfa-11e8-9c05-a19d82717978.PNG)

WP Version: 5.1-alpha-20181026.192038
GB Version: 4.3.0-alpha-3503c0d

FYI, I wasn't seeing this issue using a previous version of GB
