### ISSUE TITLE
IE11: Separators misaligned, different than other browsers

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentynineteen#438]
In IE11, the default (small) separator is centered within the screen, while in other browsers this separator is left aligned. In fact, all of the separators are centered in the screen, not centered in the content.

IE11 Separators
![small-separator-centered-ie11](https://user-images.githubusercontent.com/34601694/47807228-f4708f00-dd11-11e8-98cf-bd277f25a5bf.PNG)

Chrome Separators
![dot-separator-not-centered](https://user-images.githubusercontent.com/34601694/47807258-02261480-dd12-11e8-9e8c-33deb5029a75.PNG)

**Comment by anevins12** [comment]
How do you replicate these separators?
