### ISSUE TITLE
Add Footer Menu

### ISSUE THREAD

**Issue by 00travelgirl00** [WordPress/twentynineteen#45]
Add a Footer Menu Position, do make it easier for users to integrate a privacy menu page. In certain countries websites have to have an "Impressum" and privacy page on the websites. The footer is the mst common space to integrade it.

**Comment by melchoyce** [comment]
Could this be accomplished by styling a menu widget to fit well within the footer widget area? (#14)

**Comment by audrasjb** [comment]
Oups sorry @melchoyce for the -1 emoji, I am on my mobile and not able to change it for the moment :(((

I agree your solution can work but I'm also wondering if that wouldn't be more easily discorable in menu section since you don't have to 1) create a menu then 2) add it in a widget :)

**Comment by audrasjb** [comment]
Oups sorry @melchoyce for the -1 emoji, I am on my mobile and not able to change it for the moment :(((

I agree your solution can work but I'm also wondering if that wouldn't be more easily discorable in menu section since you don't have to 1) create a menu then 2) add it in a widget :)

**Comment by nielslange** [comment]
@audrasjb In the WP.com support we received several requests on how to add additional links behind the “Privacy Policy” link. Thus, I would say having a footer menu, in addition to the footer widget section, make sense. I’m happy to implement this later and create a PR.

**Comment by Zodiac1978** [comment]
Just wanted to add this issue as well. This is the most added little feature in my child themes for clients. +1 from me.

**Comment by nielslange** [comment]
Closed as fixed in #514.
