### ISSUE TITLE
Website Tagline is not visible on Single Blog page

### ISSUE THREAD

**Issue by burhandodhy** [WordPress/twentynineteen#48]
The Tagline is not available on blog single page http://prntscr.com/l6sbz4

**Comment by joyously** [comment]
I think that was intentional.

**Comment by burhandodhy** [comment]
It didn't make sense. 

If so, then the separator should also be removed http://prntscr.com/l6seyg

**Comment by spencerfinnell** [comment]
Related https://github.com/WordPress/twentynineteen/pull/19/files

**Comment by kjellr** [comment]
Closing this in favor of #110 because there's more recent discussion there.
