### ISSUE TITLE
Add editor styles for form elements

### ISSUE THREAD

**Issue by pbiron** [WordPress/twentynineteen#480]
Please add editor styles for basic form elements, e.g.:

* input[type=text]
* input[type=submit]
* etc

I am developing a block that generates a custom search form for a CPT.  On the front-end, the block is styled by whatever the current theme uses for such elements.

It would be great if Twenty Nineteen had editor styles for those elements so that it looked the same in the editor.

**Comment by kjellr** [comment]
Thanks, @pbiron! We're in the process of migrating Twenty Nineteen development from GitHub over to Trac, so I'm going to close this specific issue for now. This should still be discussed and addressed via your Trac issue here: 

https://core.trac.wordpress.org/ticket/45293
