### ISSUE TITLE
WooCommerce support

### ISSUE THREAD

**Issue by MarieComet** [WordPress/twentynineteen#484]
Hi,

I'm testing Twentynineteen with : 
- WordPress 5.0-beta3-43865
- WooCommerce 3.5.1

There is a CSS problem on the product single page, inside the `.summary.entry-summary` div : 
![image](https://user-images.githubusercontent.com/7976501/48005737-7bf43e80-e114-11e8-88f0-9a4385fb2aee.png)
Here is the website URL : http://gutenberg.mariecomet.fr/produit/wordpress-pennant/

**Comment by mikeyarce** [comment]
From my understanding, WooCommerce will add theme styles for the default themes in WooCommerce itself.

**Comment by nielslange** [comment]
I'll closed this issue based on https://github.com/WordPress/twentynineteen/pull/202#issuecomment-431594601:

> Historically the core themes have not had direct support for any plugins.

Also, with #202 the Jetpack support had been removed as this will be handled by Jetpack. Similar to that, the WooCommerce support will be handled by WooCommerce itself.
