### ISSUE TITLE
3 Column Gallery Widget display issues

### ISSUE THREAD

**Issue by allancole** [WordPress/twentynineteen#487]
The right padding is removed from the last image in a 3-column gallery which makes it appear larger than the other gallery images. The CSS should be revised to use an `:nth` selector for every 3rd image when a user selects a 3-column gallery. The same should happen for all other column count settings (1-9 columns). 

Screenshot: 

![image](https://user-images.githubusercontent.com/709581/48020225-63c7f380-e103-11e8-917d-01f0fba10226.png)

**Comment by briannaorg** [comment]
I'll take this one if it's unassigned
