### ISSUE TITLE
Support for Call-to-Action Block in TwentyNineteen Design Mockup?

### ISSUE THREAD

**Issue by timnicholson** [WordPress/twentynineteen#492]
In the design mockup for TwentyNineteen, there are at least 3 really nice "call to action" blocks. They have different background colors that span the full width of the browser, while nicely containing a heading, a paragraph, and a button. 

<img width="544" alt="twentynineteen_cta_block" src="https://user-images.githubusercontent.com/96018/48034045-5fabce00-e123-11e8-8388-fba5be0beb17.PNG">

However, Gutenberg sure doesn't support that. You can't even get a paragraph-only block to apply a background across the full width with the text contained. Worse, it does it by applying inline styles and there is no containing block, so it's impossible to style in the theme's stylesheet. 

For reference, a blue paragraph in standard Gutenberg block looks like this:
`<p style="color:#ffffff;text-align:center" class="has-text-color has-background has-primary-background-color"><em>
If you want to learn more about how to build additional blocks, or if you are interested in helping with the project, head over to the <a href="https://github.com/WordPress/gutenberg">GitHub repository</a>. </em></p>`

Are you planning to support full-width colored backgrounds? And in particular this "call to action" style block? If so, how do you plan to do it without coordinating with the GB folks to get them to add a class or better yet an additional div wrapper?

My website uses colored sections like that all over the place. It's a very common modern design technique. I am a theme developer, so I have control over my theme but don't see any realistic way to do this right now.

**Comment by kjellr** [comment]
Hey @timnicholson. Good question! That area was included in the mockups with the thought that [a "Section" block](https://github.com/WordPress/gutenberg/issues/4900) would be included in v5.0. That block has been recently been [pushed to 5.1 or later](
https://github.com/WordPress/gutenberg/issues/4900#issuecomment-435129232), so will not be included in the initial release. 

The closest thing available using existing blocks + styles would be either a "Media + Text block", or a solid color pull quote: 

<img width="1016" alt="screen shot 2018-11-05 at 7 55 52 pm" src="https://user-images.githubusercontent.com/1202812/48036118-e6b57200-e134-11e8-827a-8de5f45c516f.png">

Closing for now, though I could see us adding styles for a section block (if necessary) once that block launches later on.

**Comment by timnicholson** [comment]
Ok, thanks for pointing out that thread. I see there are a lot of fundamental design decisions to made and I certainly agree that we want the best possible solution **built into core**. 

I would like to suggest that for the initial release of TwentyNineteen you at least include the ability to apply the background color full-width. Meaning if a block, say a paragraph block or heading or button has a background color, that color is full-width on the page. If we at least had that and a little CSS to use padding between these colored blocks instead of margin, visually on the front-end it looks like a cohesive section. 

For example, Instead of waiting for design decisions on containers / nesting, we just put the following blocks one after the other:
1. Heading Block (w/background color)
2. Paragraph Block (w/same background color)
3. Button Block (w/same background color)

Now core folks will say that applying the background color to span the full width of the browser is theme-specific and should be done there. I agree and that's why I'm asking for it to part of this theme.

I'd honestly just add some CSS myself but there is no containing div and even the div itself doesn't have a name or CSS class or anything targetable, so it's impossible. This "feature" (weakness) in core could be addressed in the theme for now until core figures out what direction to go in strategically.

**Comment by joyously** [comment]
Is the alignwide or alignfull allowed on the existing blocks?
If so, just style those with the full width background color. If not, it's a GB problem.

**Comment by timnicholson** [comment]
Well, that brings up another issue which is that headings, paragraphs, and buttons don't have the ability to specify align wide or full. They don't seem to have ANY class assigned to them to target.

**Comment by timnicholson** [comment]
Ugh, headings don't have a color selection and buttons can't have a background color (applies the color to the button itself). I sure wish that core GB applied more of these settings to more block types. Then of course add more styles that can be targeted for further refinement of styling. 

Can anyone think of a relatively simply way to allow some full-width background coloring in TwentyNineteen to at least allow some of that primary color to sprinkled throughout the site content?

**Comment by joyously** [comment]
I think I saw a recent request for a container block and the reply was a GB issue number. Not sure if it was for 5.0 or beyond. 
Isn't there a method to put a class on any HTML? Why does it have to be a special block? I would think that alignwide would control whether the container extends to the edges and some other class would control the use of the background color. The theme can style classes for that, regardless of whether it's built-in to the editor.

**Comment by timnicholson** [comment]
> I think I saw a recent request for a container block and the reply was a GB issue number. Not sure if it was for 5.0 or beyond.
> Isn't there a method to put a class on any HTML? Why does it have to be a special block? I would think that alignwide would control whether the container extends to the edges and some other class would control the use of the background color. The theme can style classes for that, regardless of whether it's built-in to the editor.

Yes, a container block is really what is needed to be able to group a heading, paragraph, and button block together and add a background color to it like in the above design mockup for this theme. I do understand that is in development for GB, which is great. 

What I was hoping though is that this theme would still meet its design goals regardless of whatever functionality is in GB in the initial release. Meaning the theme would either provide a container or some other way to get content to look like the design mockup. That is to allow multiple blocks with background colors spanning the browser width and using horizontal padding instead of margins so that the color fills the entire group of blocks ("sections") without letting the page background create "lines" between blocks. 

So this really has nothing to do with alignwide or not. That should just control the width of the content itself (text or image or whatever). The background color shouldn't be contained regardless.

The easiest way would be a container that allowed a background color and then the theme could have that color span the browser width. But in the interim, this theme could allow all content blocks to have a background color and have that color span the browser width. Then if there are multiple blocks with the same background color in a row vertically, use some CSS to change vertical margins to padding so that they look like a single "section".

Does that make sense?

**Comment by joyously** [comment]
>  But in the interim, this theme could allow all content blocks to have a background color and have that color span the browser width.

Why don't you supply some CSS for what you want? 
As far as "theme allows blocks to have background color" : It's not up to the theme. Themes don't supply blocks. The theme can style a class, and the user can use that class. But it's best if it's a standard class, so the user isn't locked in to one theme. In my opinion, the fewer style choices made in each post, the better.
If it's not a core class, I always thought it would be best for the user to be able to enter the class name that is already in use into the Customizer, so the theme could use that name on the styles provided. But that sounds a lot like the user entering the styles themselves into the Additional CSS.

**Comment by timnicholson** [comment]
> Why don't you supply some CSS for what you want?

Well, it isn't terribly easy to do that when GB doesn't provide a container and doesn't put a class on "normal" paragraph blocks. With those constraints and no control over the theme, it's a bit beyond my CSS abilities to do it. But it would be something like this...

If I try to create the blue "call-to-action" section in the theme mockup by inputting the text and button and assigning each the primary (blue) color, the HTML is this:

```html
<p style="color:#ffffff;text-align:left" class="has-text-color has-background has-large-font-size has-primary-background-color">Redefining a brand</p>
<p style="color:#ffffff;text-align:left" class="has-text-color has-background has-primary-background-color">We help startups define a clear brand identity and digital strategy that will scale as their business grows.</p>
<div class="wp-block-button alignleft is-style-outline"><a class="wp-block-button__link" href="#">View case study</a></div>
```
 
And that looks like this:
![screen shot 2018-11-20 at 9 09 56 am](https://user-images.githubusercontent.com/96018/48783010-10c67280-eca5-11e8-92de-dcb8a2d9da4b.png)

As you can see, the background color is contained instead of spanning the full browser width. And there is vertical margin between each element, so it doesn't look like a cohesive "section".

The CSS would be something like this... To get the background color to span the browser width, apply negative margin and replace that with the same amount of padding to contain the text. 

```css
@media only screen and (min-width: 768px) {
  .entry .entry-content > p.has-background,
  .entry .entry-summary > p.has-background,
	.entry .entry-content > wp-blaock-button {
                 /*max-width: calc(8 * (100vw / 12) - 28px);*/
		margin-left: calc(-100vw / 2 + 100% / 2);
		margin-right: calc(-100vw / 2 + 100% / 2);
		max-width: 100vw;
		padding-left: calc(100vw / 2 - 100% / 2 + 100% / 12 * 2);
		padding-right: calc(100vw / 2 - 100% / 2 + 100% / 12 * 2);	
	}
}

@media only screen and (min-width: 1168px) {
  .entry .entry-content > p.has-background,
  .entry .entry-summary > p.has-background,
		.entry .entry-content > wp-blaock-button {
                 /*max-width: calc(6 * (100vw / 12) - 28px);*/
		margin-left: calc(-100vw / 2 + 100% / 2);
		margin-right: calc(-100vw / 2 + 100% / 2);
		max-width: 100vw;
		padding-left: calc(100vw / 2 - 100% / 2 + 100% / 12 * 2);
		padding-right: calc(100vw / 2 - 100% / 2 + 100% / 12 * 2);	
  }
}
```

And that looks like this:
![screen shot 2018-11-20 at 9 54 30 am](https://user-images.githubusercontent.com/96018/48785454-56396e80-ecaa-11e8-8615-f4bcaa98e8a5.png)

Then to visually group the elements together, get rid of the vertical margins.
```css
@media only screen and (min-width: 768px) {
  .entry .entry-content > p.has-background,
  .entry .entry-summary > p.has-background {
		margin-top: 0;
		margin-bottom: 0;
  }
}
```

And that looks like this:
![screen shot 2018-11-20 at 10 23 40 am](https://user-images.githubusercontent.com/96018/48788437-72400e80-ecb0-11e8-859c-f6e889780ea7.png)

But that is as far as I can go with the CSS. There is too much padding still between rows, so some complex first-child and last-child logic would need to be added. It would need to target elements where the same background color appears multiple times in a row. 

And there is no way in GB to specify a background color in a button block, so there is no way for the user to specify that.

As to the rest of your comments, I totally agree. There shouldn't have to be theme-specific styles needed and certainly users shouldn't have to enter hard-coded class names into the additional CSS classes block. This theme should "automatically" style blocks with background colors to have that color span the browser width. That is exactly what the theme design mockups depict. If the user switches themes, then most likely the theme would just contain the background color within the normal width of the theme. 

But these colored "sections" that span the browser width in the design mockup are the coolest part of this theme's design, IMHO. So I would love to see this feature in the theme.

It sounds like we will just have to wait until GB provides a container block, but at the very least I'd like to raise visibility to this here so that when they do provide that, this theme would be updated to style it like the design mockup.

Also note that I've used blue in this example here, but the theme mockup shows back and gray background colors as well. So those would need to be added to the theme's color palette.

**Comment by joyously** [comment]
It really seems like the content is not the theme's responsibility.
Couldn't the same effect be achieved by viewing the HTML version and adding a `<div class="alignfull has-primary-background-color">  </div>` around it? That is not the theme's job. But it's likely to look pretty close to the mockup with something like that.

_I don't get why everyone wants full width things. They look wrong to me._

**Comment by timnicholson** [comment]
Huh? Are you really saying that it isn't the theme's job to style the content according to the theme's design mockup? I would say that is precisely what the theme's job *is*.

Also, you can't just place a div around it in the HTML view. The GB editor won't let a div span blocks. It adds an ending div right after your beginning div so it has no effect on anything.

Does it matter what an individual thinks of the design mockup? The theme is supposed to match the design, right? Otherwise, what is the point of having a design? Just let each individual coder do whatever they want?

**Comment by kjellr** [comment]
Hello again. This discussion is getting a bit out of hand. 

To circle back to the original purpose of this ticket: The design comps featured a full-width area that included a call to action. That was using the [Section (or, "Container") Block](https://github.com/WordPress/gutenberg/issues/4900), which was originally planned for release with 5.0. That block has since been pushed back to 5.1, so the Twenty Nineteen will not ship with support for it. Once the Section block is available in Gutenberg, Twenty Nineteen should be updated to support it.
