### ISSUE TITLE
Custom HTML block does not have margins

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#499]
The Custom HTML block is too far left, no margin like the other blocks.

![custom-html-block](https://user-images.githubusercontent.com/7957680/48100020-453b2880-e1e7-11e8-9269-cbe590e1b51a.jpg)

**Comment by colorful-tones** [comment]
I tried reproducing this issue, but was not able to. 

I even tried reproducing the order of the blocks thinking that might affect, but still could not reproduce the margins. 

I suspect that the "The classic block" using the Classic block might have had invalid markup, which might have affected the row below it: "The custom HTML block" (that used the Custom HTML block).

![Gutenberg editor view](https://user-images.githubusercontent.com/405912/48161274-22247d80-e2a8-11e8-9d03-2105c9095a3b.png)

![TwentyNineteen output view](https://user-images.githubusercontent.com/405912/48161281-294b8b80-e2a8-11e8-8748-255b2d75be6c.png)

<sup>Tested with: Chrome 70.0.3538.77 on macOS 10.14 (18A391)</sup>

**Comment by joyously** [comment]
@carolinan Can you try this? _(I used the proposed block version of theme unit test data.)_

**Comment by carolinan** [comment]
I have not been able to reproduce this, neither with the theme unit test nor when creating a new post,
with and without blocks above it.  (Only tested on win10 with chrome 70.0.3538.77 and Firefox 63.0.1 with  WP 5.0-beta3-43878)
![htmlblock](https://user-images.githubusercontent.com/7422055/48243066-9d884b00-e3de-11e8-9b51-a33b58d20998.png)

**Comment by joyously** [comment]
I just now got the latest and tried it on 4.9.8, both with and without GB. It looks fine now.
