### ISSUE TITLE
wide embed is chopped

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#500]
This is a Twitter embed, wide width. 
In my SeaMonkey, the text is chopped on the left, and no real embed happens.

![wide-embed-chopped](https://user-images.githubusercontent.com/7957680/48100202-dc07e500-e1e7-11e8-8d20-2a7e2a0039d6.jpg)

In my Firefox, it looks like an embed. Is it wide?

![wide-embed-firefox](https://user-images.githubusercontent.com/7957680/48100399-b62f1000-e1e8-11e8-9beb-c6860c6d9e76.jpg)

**Comment by joyously** [comment]
I'm seeing that the Twitter and Facebook embeds do not expand in SeaMonkey, but they do in Firefox. I tested with another theme (my own, so I know what it's doing), and get the same result, although not chopped.

**Comment by carolinan** [comment]
In Chrome Version 70.0.3538.77 on Win 10, I can see that the twitter embed block is chopped off on the left side, as in the screenshot above, until the page has fully loaded.
I tested the block with all available alignments and the block is chopped off in all of them,
It is not chopped off in the editor.

When I test it in Twenty Seventeen, the block is fully visible even while loading:
![twentyseventeen-embed](https://user-images.githubusercontent.com/7422055/48244223-f9ee6900-e3e4-11e8-8ea2-39d2dcf102d3.png)

**Comment by kjellr** [comment]
@joyously or @carolinan — would you mind re-testing now that #597 has merged? I'm not 100% sure that'll solve the issue you're seeing, but it seems somewhat likely. 🙂 Thank you!

**Comment by joyously** [comment]
Looks fixed to me.

**Comment by kjellr** [comment]
Great, thanks for confirming!
