### ISSUE TITLE
Invalid RGBAs within Sass files

### ISSUE THREAD

**Issue by smy315** [WordPress/twentynineteen#518]
Although the build tool fixes the invalid RGBA placed within some of the Sass files, we shouldn't be using invalid syntax and rely on a build tool fix the invalid values. Some places within the codebase uses valid RGBAs but found couple that are invalid. 

For example, rgba(#000, 0.35) is not a valid RGBA found in https://github.com/WordPress/twentynineteen/blob/da4955bbbe35f482bb28bc7cf17e1b662b655e81/sass/site/primary/_posts-and-pages.scss#L146.

This is an example of valid RGBA: https://github.com/WordPress/twentynineteen/blob/da4955bbbe35f482bb28bc7cf17e1b662b655e81/sass/modules/_accessibility.scss#L17.

**Comment by smy315** [comment]
PR for this issue: https://github.com/WordPress/twentynineteen/pull/519

**Comment by kjellr** [comment]
Fixed via #519.
