### ISSUE TITLE
active submenu is wider than non-active

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#529]
It's difficult to determine which menu issues have been fixed, but I just downloaded the latest master, and I'm seeing the active state on submenus has a wider width than the normal state. Is this intentional?

![active-submenu-grows-2018-11-09 08-54](https://user-images.githubusercontent.com/7957680/48269657-c4a24500-e3fd-11e8-92db-5399e7b9af3a.gif)

**Comment by allancole** [comment]
This should be fixed in #485

**Comment by kjellr** [comment]
> This should be fixed in #485

Confirmed. I'm not seeing this behavior any more: 

![menu](https://user-images.githubusercontent.com/1202812/48440475-019c6d80-e757-11e8-9212-10cece32ef5b.gif)

I'm going to go ahead and close this one.
