### ISSUE TITLE
gallery thumbnails sometimes overlap

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#531]
I'm not sure what to make of this overlap of images in a seven column gallery shortcode. I was thinking it was the long words in the descriptions, but the 8 and 9 column ones did not overlap.  So it _could_ be column math with a prime number...
This is Firefox 63, at 846px width (at least that's the width of the screenshot).
WP 4.9.8, GB 4.2

![post format gallery page 2 local cu -4051](https://user-images.githubusercontent.com/7957680/48272378-1057ed00-e404-11e8-8bde-8f7f084103f5.jpg)

**Comment by kjellr** [comment]
I can reproduce — I think the math for this needs another pass. 

Also worth noting that the display of these classic galleries within Gutenberg is incorrect as well:

![screen shot 2018-11-12 at 12 53 14 pm](https://user-images.githubusercontent.com/1202812/48365850-135c1300-e67a-11e8-8b73-6257e96b98fe.png)

**Comment by kjellr** [comment]
> Also worth noting that the display of these classic galleries within Gutenberg is incorrect as well:

After doing some more digging, this is definitely a bug that effects other themes. I've filed a bug report for it here: https://github.com/WordPress/gutenberg/issues/11940

In the meantime, I think we should remove Twenty Nineteen's (currently broken) editor styles for galleries within the classic editor block:

https://github.com/WordPress/twentynineteen/blob/336a1f4acdf1229ef226b180ea16e2cb310084d0/style-editor.scss#L698-L720

Those should be introduced via Gutenberg anyway, and our styles will interfere once that's fixed.

The original front-end issue reported in this thread it still valid and should be fixed though.

**Comment by kjellr** [comment]
@joyously Would you mind re-testing this? I'd been able to reproduce this before, but unable to anymore: 

![screen shot 2018-11-16 at 20 31 34](https://user-images.githubusercontent.com/1202812/48654919-e8a5ed80-e9de-11e8-9a6d-bc9893c56fa7.png)

FF 63.0.1 @ 846px wide. I see the same in Chrome + Safari.

**Comment by joyously** [comment]
It's still there for me, on a variety of window sizes, but only the seven column gallery. What is in your screenshot? 6 or 7? 
I am seeing the 7 column gallery show 6 columns, and then have an overlap problem, sometimes.
 
WP 4.7.11, no GB
This is at 1028px
![gallery-overlap-1028w](https://user-images.githubusercontent.com/7957680/48662783-8e437600-ea4c-11e8-9d9f-362e0d981284.jpg)

WP 4.9.8, no GB
This is at 770px, silightly different data
![gallery-overlap-770w](https://user-images.githubusercontent.com/7957680/48662786-94395700-ea4c-11e8-9b44-574f8702c7ca.jpg)

WP 4.9.8, GB 4.4.0
This is at 962px
![gallery-overlap-962w-gb](https://user-images.githubusercontent.com/7957680/48662852-b089c380-ea4d-11e8-977e-02cc0176b3b4.jpg)

**Comment by kjellr** [comment]
Thanks for the clarification there, @joyously! I can reproduce with the 7 columns, but not the 6 columns, as you noted. I've pinpointed the issue and will have a fix up shortly. 👍
