### ISSUE TITLE
Better code oraganisation in template-functions.php

### ISSUE THREAD

**Issue by grappler** [WordPress/twentynineteen#548]
The header in the `template-functions.php` is 
> Functions which enhance the theme by hooking into WordPress

For me I understand this that all of the functions within `template-functions.php` should hook into either a filter or action.

This is the case for the following functions.
- `twentynineteen_can_show_post_thumbnail()`
- `twentynineteen_image_filters_enabled()`
- `twentynineteen_post_thumbnail_sizes_attr()`
- `twentynineteen_get_avatar_size()`
- `twentynineteen_is_comment_by_post_author()`
- `twentynineteen_get_discussion_data()`
- `twentynineteen_hsl_hex()`

These are helper functions that would fit best in a file like `helper-functions.php`.

I think `twentynineteen_add_dropdown_icons()` could be moved to `icon-functions.php` to join `twentynineteen_nav_menu_social_icons()`

**Comment by joyously** [comment]
I think the description doesn't match the file name. Template functions are those functions that are used to output HTML in a template file. Actions and filters are not template functions, they are hooks.

**Comment by grappler** [comment]
> Template functions are those functions that are used to output HTML in a template file.

That is what `template-tags.php` is for. This is where Template Tags comes from: https://developer.wordpress.org/themes/basics/template-tags/

**Comment by joyously** [comment]
Then call the file hooks.php instead of template-functions.php which is ambiguous.

**Comment by joyously** [comment]
Or put them all in functions.php, because there are functions in there that hook to actions.

**Comment by allancole** [comment]
@grappler I agree that a file like `helper-functions.php` might be appropriate for the functions you mentioned that don’t actually hook into WordPress. 

>> Or put them all in functions.php, because there are functions in there that hook to actions.

> I don't think that is a good otherwise we will have a really big functions.php

Twenty Sixteen has a really huge `functions.php` file and I think we should avoid that the same way we did in Twenty Seventeen where `template-functions.php` acts like a continuation of `functions.php`. We could rename the file, but since we’re using it the same way Twenty Seventeen does, I don’t think its worth changing it.

**Comment by allancole** [comment]
I've moved this issue over to Trac here:

https://core.trac.wordpress.org/ticket/45984

I'll close this issue for now, and we can continue discussion in that thread. 

Thanks!
