### ISSUE TITLE
Missing i18n for m-Dash between title and site description

### ISSUE THREAD

**Issue by pixolin** [WordPress/twentynineteen#557]
In German and French typography, the usage of m-Dash for text-separation is uncommon. A …

> … "space, en dash, space" sequence is also the predominant style in German and French typography. ([Wikipedia](https://en.wikipedia.org/wiki/Dash#Spacing_and_substitution))

By [hardcoding the m-Dash into the stylesheet](https://github.com/WordPress/twentynineteen/blob/master/sass/site/header/_site-header.scss#L121), the typography can't be adjusted according to regional typographic standards. Instead the [template-part for site-branding](https://github.com/WordPress/twentynineteen/blob/master/template-parts/header/site-branding.php) should have a translation function.

**Comment by kjellr** [comment]
Thanks for highlighting this, @pixolin. We're already thinking about how the em dash is added as per #451, so this is something to consider as we tackle that issue.

**Comment by kjellr** [comment]
Closing, since this ticket has been migrated over to Trac here: https://core.trac.wordpress.org/ticket/45924
