### ISSUE TITLE
Elipsis Icon shows in menu on all Screen sizes

### ISSUE THREAD

**Issue by pixolin** [WordPress/twentynineteen#558]
No matter how long the menu is, I see an ellipsis icon (svg) (circle with three dots) behind the last menu entry, viewing the web page on my desktop monitor:

<img width="414" alt="screenshot_352" src="https://user-images.githubusercontent.com/1968542/48349733-566fb380-e685-11e8-9c00-17494e510a51.png">

If I edit the menu in the customizer, same icon shows up twice.

<img width="679" alt="screenshot_351" src="https://user-images.githubusercontent.com/1968542/48349755-6ab3b080-e685-11e8-8cb9-e822681345e1.png">

**Comment by kjellr** [comment]
Fixed via #589 👍
