### ISSUE TITLE
Visited links with a button class have the same value for color and background properties

### ISSUE THREAD

**Issue by wvega** [WordPress/twentynineteen#567]
I noticed that the text from any visited link with the class `button` can no longer be read because the links are styled using the same value for `color` and `background-color` properties:

<img width="746" alt="screen shot 2018-11-12 at 3 21 28 pm" src="https://user-images.githubusercontent.com/45068/48373121-d3ebf180-e68e-11e8-984d-39e76d82b463.png">

**Is this a use case that should be covered by the theme's stylesheet? or should I avoid using the `button` class on links?**

---

Twenty Seventeen, Twenty Sixteen, Twenty Fifteen, Twenty Thirteen, Twenty Twelve, Twenty Eleven and Twenty Ten don't seem to provide CSS rules for the `button` class. The links are displayed as regular links:

**Twenty Seventeen**
<img width="548" alt="screen shot 2018-11-12 at 3 24 52 pm" src="https://user-images.githubusercontent.com/45068/48373214-2a593000-e68f-11e8-8a05-badef8935dda.png">

However, Twenty Nineteen, Twenty Fourteen and several custom themes include rules to display those links as buttons:

**Twenty Fourteen**
<img width="502" alt="screen shot 2018-11-12 at 3 27 26 pm" src="https://user-images.githubusercontent.com/45068/48373601-47423300-e690-11e8-860c-713ac48df5d9.png">

**i-Spirit**
<img width="670" alt="screen shot 2018-11-12 at 3 31 17 pm" src="https://user-images.githubusercontent.com/45068/48373596-414c5200-e690-11e8-8cc7-b902b4467a61.png">

**OceanWP**
<img width="627" alt="screen shot 2018-11-12 at 3 35 39 pm" src="https://user-images.githubusercontent.com/45068/48373711-a56f1600-e690-11e8-91f3-9897253652e4.png">

**Comment by kjellr** [comment]
Should be all set now that #600 has been merged. Thanks!
