### ISSUE TITLE
Black filter missing on blog page

### ISSUE THREAD

**Issue by xpurichan** [WordPress/twentynineteen#570]
**Summary:**
Applying the black filter to featured images results in only featured images on the individual post page from using this filter. When viewing these featured images from the main blog page they have no filter.

**Steps to reproduce:**
1. Go to Customize > Colors
2. Under Color Scheme choose _Custom_
3. Apply the **Black Filter** to your featured image

**Expected behavior:**
I expect the black filter should be applied to featured images on the blog roll and individual post pages. I expect this because if I use the colored filter option then it is applied at both of these location.

**Actual behaviour:**
The black filter only applies to the featured image when viewed from the individual post page. The filter does not get applied to the featured image on the blog roll.

**Screenshots:**

Colored filter -
 * Blog roll: 
![screen shot 2018-11-12 at 7 35 46 pm](https://user-images.githubusercontent.com/33190975/48384961-35718780-e6b2-11e8-8055-311c6ff5f7a5.jpg)

 * Individual post:
![screen shot 2018-11-12 at 7 35 08 pm](https://user-images.githubusercontent.com/33190975/48384965-399da500-e6b2-11e8-9a0a-71fe3f1d0ba1.jpg)

--

Black filter -
 * Blog roll: 
![screen shot 2018-11-12 at 7 36 00 pm](https://user-images.githubusercontent.com/33190975/48384976-46ba9400-e6b2-11e8-90da-8cf4f3fd19c8.jpg)

 * Individual post:
![screen shot 2018-11-12 at 7 23 34 pm](https://user-images.githubusercontent.com/33190975/48384978-49b58480-e6b2-11e8-907a-dcd1a36a5a25.jpg)

**Comment by xpurichan** [comment]
Oh goodness, I clearly missed the description. I'm sorry about that. I think the wording is mostly clear, but it is easy to look past.

I don't think it makes sense to say _If you disable this effect_ though, because we're not choosing any option that says "Disable". I think it would make more sense to say something like: _If you enable the black filter_.

**Comment by kjellr** [comment]
> I don't think it makes sense to say If you disable this effect though, because we're not choosing any option that says "Disable". I think it would make more sense to say something like: If you enable the black filter.

That's true. 

In any case, what do people think of simplifying down to an approach like this: 

![screen shot 2018-11-13 at 3 02 38 pm](https://user-images.githubusercontent.com/1202812/48439826-3f989200-e755-11e8-88c0-1b8fa611b6a0.png)

This sort of sidesteps the issue by avoiding mention of the black overlay at all. Instead, it's just a binary option: You're either choosing to use a colored filter on your images or you're not. It also uses _much_ less text, which seems like a solid improvement to me.

**Comment by LittleBigThing** [comment]
We have considered [using a checkbox](https://github.com/WordPress/twentynineteen/pull/327#issuecomment-433195957), but didn't explore it further. I like the idea of simplifying it.

It would make translating the text easier for some languages when compared to the current implementation.

**Comment by allancole** [comment]
Yeah, I like the checkbox idea—much easier to communicate what this option does this way. 👍

**Comment by LittleBigThing** [comment]
I’ll try to put together a PR with the proposed text later today.

**Comment by LittleBigThing** [comment]
See #598 for the proposed changes.

When doing changes I noticed that there is no 'title' for a checkbox as for other controls (because the label is the title in other cases). So I felt free to leave it out and use the description for the label.

<img width="270" alt="screenshot 2018-11-14 at 21 54 33" src="https://user-images.githubusercontent.com/5901923/48511812-190f4f80-e858-11e8-9189-0a4aa93eb0ae.png">

<img width="273" alt="screenshot 2018-11-14 at 21 54 21" src="https://user-images.githubusercontent.com/5901923/48511819-1e6c9a00-e858-11e8-948a-eca52fa6b882.png">
