### ISSUE TITLE
Can't click arrow icons of the posts navigation on mobile devices.

### ISSUE THREAD

**Issue by youthkee** [WordPress/twentynineteen#578]
On mobile devices(under 768px screen), Prev text "Newer posts" and Next text "Older posts" are disappeared.
Then only arrow icons`<`and`>`are displays at both ends of the navigation.
But when touching just apon these icons, prev and next links doesn't work.
I think it is because svg elements inside of a elements can not behave as a link.
What is a better solution for that?

*I checked on Mobile Safari and iOS Simulator(iOS 11.4).

<img width="233" alt="twentynineteen-posts-format" src="https://user-images.githubusercontent.com/319783/48413471-2f9ba500-e78b-11e8-9541-2f0a8897bc17.png">

**Comment by 2ndkauboy** [comment]
An SVG inside of an a tag sould usually be clickable. We probably want to keep them. I'll check that with some devices as well.

**Comment by kjellr** [comment]
Fixed via #572 and #589 🎉
