### ISSUE TITLE
Extra spacing when a non-linked custom menu is added

### ISSUE THREAD

**Issue by dartiss** [WordPress/twentynineteen#587]
This can be recreated by adding a menu option to the primary menu, which is a custom link which doesn't link to anything (creating a non-clickable menu option). When you then add sub-menus to it, extra spacing is added to the top (I'm guessing representing the non-clickable primary menu option).

Here's a test on my site demonstrating this...

<img width="498" alt="screenshot 2018-11-13 at 21 43 45" src="https://user-images.githubusercontent.com/14928971/48444975-58bd3500-e78d-11e8-89ff-f4e775b45ec0.png">

**Comment by dartiss** [comment]
Also, that icon on the right - the horizontal 3 dots. Should that be displaying permanently? It looks to me to be something that should only appear if the menu is collapsed - maybe I'm confused about its purpose.

**Comment by kjellr** [comment]
Thanks for the report. I opened #588 to hopefully take care of this. 

> Also, that icon on the right - the horizontal 3 dots. Should that be displaying permanently? It looks to me to be something that should only appear if the menu is collapsed - maybe I'm confused about its purpose.

Yes, that's a bug. It's being tracked in #558.

**Comment by dartiss** [comment]
Thanks @kjellr - hadn't noticed the ellipsis bug had been reported elsewhere (I had looked but without releasing it was actually called an "ellipsis icon", I came up blank 😆)
