### ISSUE TITLE
Implement a better font-family solution for non-latin languages

### ISSUE THREAD

**Issue by mako09** [WordPress/twentynineteen#602]
I think that 635a5bb of #383 is very rough.
In the non-latin languages, the situation that all `font-family` are unified into only one is unbearable.
Especially `<code>` and `<pre>` should be `monospace` even in non-latin languages.

I propose more fundamental solution.  The size of style.css will be larger than now, but I believe that maintenance is not so difficult.

A patch is attached.
This patch is merely to show the direction of the solution and is not complete.
Therefore, only the part related to $font__body and only about a few languages are described.

https://gist.github.com/mako09/bf919903b7e4476279e77d2d0c2d9099

**Comment by mako09** [comment]
* update the patch.
  * implement for $font__heading

https://gist.github.com/mako09/bf919903b7e4476279e77d2d0c2d9099

**Comment by kjellr** [comment]
Hey @mako09! We're in the process of closing down this GitHub repository now that the theme is merged into core, so I've migrated this issue (along with the fix from #728) over to Trac:

https://core.trac.wordpress.org/ticket/45731

I'm closing this issue a result. Please feel free to follow up in the new thread moving forward.

Thanks again for all your work on this!
