### ISSUE TITLE
Embed: WordPress.tv: left-aligned and right-aligned embeds are sized differently on the front-end

### ISSUE THREAD

**Issue by designsimply** [WordPress/twentynineteen#610]
Steps to reproduce:

1. Create a post and add a few paragraphs.
1. Add a left-aligned WordPress.tv embed.
1. Add a right-aligned WordPress.tv embed.
1. Compare how the embeds look in the editor versus the front-end.

<strong>Result:</strong> I expected the sizes of the left-aligned and right-aligned WordPress.tv embeds to approximately match what I see in the editor but the sizes do not match.

![screen shot 2018-11-15 at 5 35 35 pm](https://user-images.githubusercontent.com/1119271/48590725-d99b3e80-e8fd-11e8-8c50-d75e71fdbb4e.png)

![screen shot 2018-11-15 at 5 35 37 pm](https://user-images.githubusercontent.com/1119271/48590779-1830f900-e8fe-11e8-9d4b-1f6db2666c40.png)

<sup>Seen at https://madefortesting.com/wp-admin/post.php?post=694&action=edit and https://madefortesting.com/wordpress-tv-embed/ using WordPress 5.0-beta4-43896 and Twenty Nineteen `46da458` using Firefox 63.0.1 on macOS 10.13.6</sup>

Notes: I tested both with the latest `master` versions of WordPress and Twenty Nineteen (seen in the screenshots above) as well as with WordPress 4.9.8 and Gutenberg 4.4 `cdeb40986` and Twenty Nineteen and saw the same result for both. I checked the WP5.0 site in Chrome and Safari on macOS and saw the same result. I also viewed the same post with Twenty Seventeen and found the sizes match for that theme ([screenshot](https://user-images.githubusercontent.com/1119271/48590929-b8871d80-e8fe-11e8-991f-fef51aba8a50.png)).

Feels like a minor issue. 🙂 Feel free to close if so.

**Comment by kjellr** [comment]
Thanks for the report, and for the detailed description of the problem. 

> The best way to test for precision accuracy, then, is to enable fullscreen mode and dismiss the sidebar. This would be the closest representation we can get, and even there it's not likely to be perfect due to limitations in the editor style system.

This is accurate. I'm going to go ahead and close this issue with that recommendation. We'll be archiving this repository shortly and moving to Trac, so if we'd like to discuss further, we can do so in a new ticket there: 

https://core.trac.wordpress.org/newticket

Thank you!
