### ISSUE TITLE
Cover blocks does not look the same in the editor and on the front.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentynineteen#612]
The size of cover blocks with a left align does not match the editor, the blocks on the front are much narrower. 
-Do we want text to break this way?
-The right align looks OK.

Chrome version 70.0.3538.102 on pc, win 10:
Image background:
![left-comparison](https://user-images.githubusercontent.com/7422055/48597770-bb662a80-e95f-11e8-9dee-6c0707f16c56.png)

Video background:
![video-comparison](https://user-images.githubusercontent.com/7422055/48597705-5d394780-e95f-11e8-8b77-f941de359a36.png)

Right aligned coverblock for comparison:
![right-coverblock-front](https://user-images.githubusercontent.com/7422055/48597068-231a7680-e95c-11e8-8c10-39a496f7984f.png)

When the cover blocks are centered, and the text has a right or left alignment, then there is no space around the text:
![centered-blocks](https://user-images.githubusercontent.com/7422055/48597880-70004c00-e960-11e8-9766-1943b3b4364a.png)

Video background:
![coverblock-text-right-front-video](https://user-images.githubusercontent.com/7422055/48597527-8d341b00-e95e-11e8-9a22-700ba5595d66.png)

**Comment by kjellr** [comment]
Hi @carolinan — can you confirm which version of the theme you're seeing this in?  Many of these issues should've been fixed in https://github.com/WordPress/twentynineteen/pull/559, which is included in last night's 5.0 Beta5 update. 

Thanks!

**Comment by carolinan** [comment]
I am using 5.0-beta5-43907.

**Comment by kjellr** [comment]
Thanks, that's helpful. I'm able to reproduce most of this, and will open a PR shortly. 👍

**Comment by kjellr** [comment]
The center-alignment bugs mentioned are actually coming from Gutenberg. I've pushed a fix in via 
https://github.com/WordPress/gutenberg/pull/11990

The rest should be taken care of in #619. 👍
