### ISSUE TITLE
Customizer Pimary Color: Hexidecimal input

### ISSUE THREAD

**Issue by josephdickson** [WordPress/twentynineteen#613]
Feature Request

**Problem:** It's not possible to precisely select the *Primary Color* in the Customizer. Users have to slide back and forth then inspect with their browser and try to trap the specific color they might desire.

![color slider](https://user-images.githubusercontent.com/9701927/48598765-5ab3ff00-e919-11e8-9c00-57771ba255f0.png)

**Desired Solution:** Add a hexidecimal input box that can be used to override the color slider if desired.

**Current work around:** Use CSS to override colors manually in a Child Theme or the Additional CSS Customizer Box. However, this requires a lot of inspection and testing.

**Comment by kjellr** [comment]
Hi, @josephdickson — Thanks for the report. 

Twenty Nineteen's [original custom color implementation](https://github.com/WordPress/twentynineteen/pull/113#issuecomment-432421717) allowed for users to enter a Hex value, as shown in the GIF here: 

![47083306-78098680-d210-11e8-8a49-e18b08bf9cc7](https://user-images.githubusercontent.com/1202812/48626167-312dbe80-e97f-11e8-95e6-aba798633cca.gif)

This was problematic in that it opened the door to very inaccessible color combinations throughout the site. We looked into the addition of [a color contrast checker](
https://github.com/WordPress/twentynineteen/pull/113#issuecomment-432283636) to warn users about that, but ultimately abandoned that idea after considering the bulk and complexity it'd add to the theme. 

In the end, we [borrowed a solution from Twenty Seventeen](
https://github.com/WordPress/twentynineteen/issues/191#issuecomment-432059636), and implemented a color hue picker instead. This allows people to customize the color while also guiding them towards a more accessible palette. 

Switching to a hex color picker isn't something @allancole and I are looking to change before the release at this point, but I could definitely imagine a separate plugin or child theme handling this sort of thing.

**Comment by josephdickson** [comment]
That's a pretty good reason. Thanks for the reply.
