### ISSUE TITLE
Customizer keeps reloading if a menu with an invalid page is used

### ISSUE THREAD

**Issue by BevS** [WordPress/twentynineteen#616]
If you create a menu, then delete one of the pages the menu is left with an "invalid page" entry. If this menu is active in most themes, it is fine. But in Twenty Nineteen the Customizer screen refreshes infinitely. I tracked it to a call in priority-menu.js:

		if ( hasSelectiveRefresh ) {
			// Force a full refresh on partial content renders to re-run updateNavigationMenu()
			wp.customize.selectiveRefresh.bind('partial-content-rendered', function () {
				wp.customize.preview.send('refresh');
			});
        }

**Comment by kjellr** [comment]
I can confirm this. Steps to reproduce: 

1. Create a page
2. Add it to the menu
3. Delete the page
4. Open the customizer

You'll currently see something like this:  

![deleted-page](https://user-images.githubusercontent.com/1202812/48655081-ddec5800-e9e0-11e8-8c43-2e9c9a151c6a.gif)

cc @allancole — we should try and get this sorted out before RC1.
