### ISSUE TITLE
Consider setting background color and foreground color together

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#64]
https://github.com/WordPress/twentynineteen/blob/7b1170c700b51ccc89479a5552c97102832b2d77/style.css#L622-L624

To ensure correct contrast, background color and foreground color should always be set together.
There are other instances of this also.

**Comment by celloexpressions** [comment]
I agree that a default color should be defined alongside the default body background here.

**Comment by laurelfulford** [comment]
This issue has been moved to Core Trac, so I'm going to close this one:

https://core.trac.wordpress.org/ticket/45916
