### ISSUE TITLE
Category and Archive widget blocks do not respect aligncenter on frontend

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentynineteen#644]
Both the category and archive widget blocks do not align there lists in the center when aligncenter is selected, on the frontend. While the backend shows the lists aligned in the center. See screenshots below

Backend
![categories-aligncenter-backend](https://user-images.githubusercontent.com/34601694/48729781-757ec000-ec06-11e8-830a-f3cef9f93b0f.PNG)

Frontend
![categories-aligncenter-frontend](https://user-images.githubusercontent.com/34601694/48729788-7dd6fb00-ec06-11e8-8608-e40440e5e803.PNG)

The archive widget block displays exactly the same as the category widget block.

WP Version: 5.1-alpha-20181026.192038
GB Version: 4.4
TwentyNineteen: Latest version, up to date with latest commits, as of posting this issue.

**Comment by joyously** [comment]
I think the block itself should be centered, not the individual lines. Centered text is difficult to read.

**Comment by richtabor** [comment]
Here's what the .aligncenter blocks look like, with a child category ("sub category") in that PR:

<img width="712" alt="screen shot 2018-11-28 at 12 37 27 pm" src="https://user-images.githubusercontent.com/1813435/49170551-671d5c00-f30a-11e8-9e83-865ee8c39c21.png">
