### ISSUE TITLE
Theme is not available in theme search 

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/twentynineteen#645]
The Theme isn't found in the theme search although [readme directs users to install it that way](https://github.com/WordPress/twentynineteen#installation). 

to reproduce: 
1. go to https://wordpress.org/themes/search/
2. search twenty nineteen. 

[No results are returned
](https://wordpress.org/themes/search/twenty%20nineteen/)

![image](https://user-images.githubusercontent.com/955351/48731898-1fad1680-ec0c-11e8-9c97-74a8fbda26c6.png)

**Comment by joyously** [comment]
It's not released yet.

**Comment by skorasaurus** [comment]
now available.
