### ISSUE TITLE
Defer script loading to improve performance and follow modern best-practice

### ISSUE THREAD

**Issue by mor10** [WordPress/twentynineteen#647]
See #646

`twentynineteen-priority-menu` and `twentynineteen-touch-navigation` should be deferred to improve performance and follow [modern JS loading best-practice](https://developers.google.com/speed/docs/insights/BlockingJS). The above PR introduces `async`/`defer` capabilities which should be used for all enqueued JS on the front end in place of loading in footer.

**Comment by crunnells** [comment]
We're opting not to add this functionality at this time, as there's still some discussion in `core` about the best way to implement `async` and `defer`. 

Since we're closing out this repo to move the theme development fully to the Core Trac, I'm going to close this issue. Thanks!
