### ISSUE TITLE
Social Menu icons don't line up with the site logo when no menu is present

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#649]
On breakpoints greater than `768px`. 

To reproduce: 

1. Add a site icon.
2. Unassign a menu to the "Primary" menu location.
3. Create a social menu
4. Notice that the social menu does not line up cleanly with the site icon. 

<img width="414" alt="screen shot 2018-11-20 at 9 37 34 am" src="https://user-images.githubusercontent.com/1202812/48780477-ff329a00-eca7-11e8-863e-ba8c3e706f0a.png">

**Comment by mrxkon** [comment]
:wave:  this is the preview of #652 

![screenshot from 2018-11-20 22-59-31](https://user-images.githubusercontent.com/22611066/48802546-3345a380-ed18-11e8-8e4f-985244969363.png)
