### ISSUE TITLE
Links within solid-color pullquotes aren't visible in the editor

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#650]
To reproduce: 

1. Create a solid color pullquote block
2. Add a link to that block
3. See error

![pullquote-link](https://user-images.githubusercontent.com/1202812/48780804-bdeeba00-eca8-11e8-993f-cfefdcc4173d.gif)

Note: These appear fine on the front end: 

<img width="752" alt="screen shot 2018-11-20 at 9 44 51 am" src="https://user-images.githubusercontent.com/1202812/48780922-f68e9380-eca8-11e8-8a3f-4ec59f0321ed.png">

**Comment by mrxkon** [comment]
@kjellr This simple PR adds a default **white** color to **a** when a user selects the **Solid Color** style. ( I didn't see anything else needed for this to be honest but feel free to comment and I'll update if needed :) )
