### ISSUE TITLE
Widget titles should NOT be H2 tags

### ISSUE THREAD

**Issue by slaFFik** [WordPress/twentynineteen#658]
Post titles in a blog view have `H2` tag. Having the same for not a content, but just widget titles steal the value from posts. I know that this is inside `aside` tag, but I'm not sure that Google (and other less significant search engines) pay too much attention to `article`, `aside` when calculating ranking of the post.
It should be at maximum `H3`, ideally even `H4`.

![image](https://user-images.githubusercontent.com/282234/48941274-88a1d080-ef23-11e8-927f-abf8827f7682.png)

I'm on WordPress Nightly Build, `5.0-RC1-43944`.

**Comment by joyously** [comment]
I agree this can be a problem. I don't know why the default for widget titles is h2. But the theme can easily change it to be h3 or h4.
Is the site title always h1? Or is it a `<p>` and the page title is h1?

**Comment by LittleBigThing** [comment]
> Is the site title always h1? Or is it a `<p>` and the page title is h1?

The site title is a `<p>` on other pages than the homepage.

I would stick to h2 for the widget title, but I agree that they could be smaller visually.

**Comment by LittleBigThing** [comment]
> Is the site title always h1? Or is it a `<p>` and the page title is h1?

And the page title is then `<h1>` indeed.

**Comment by kjellr** [comment]
> I am checking twentyfifteen, twentysixteen, and twentyseventeen. All are using h2 for widget titles. However the font size for the h2 widget title should be smaller. Like 1rem instead of 2.25em

I think we should stick with h2, for this reason. 

I'm okay with trying a smaller widget title font size (See PR https://github.com/WordPress/twentynineteen/pull/671), but I'm not 100% sure it makes sense to squeeze that in while we're in RC.

**Comment by slaFFik** [comment]
It's a new theme, not a child theme for 2015-2017. Why preserve this (imo incorrect) approach by using "they've done like that" excuse? 
Semantically - this is a mistake.

**Comment by kjellr** [comment]
I appreciate the continued response here, but using a `h3` or `h4` here doesn't seem like a solid solution to me. 

To expand on my short note above: The theme is making an effort to have the post/page title be the only `h1`, which leaves us with a headings structure like this by default (if a user has added no headings to post content): 

1. `h1` Page Title
2. `h2` Widget Title

If we changed the widgets to `h3` or `h4`, it's likely that there would be no `h2` tags at all on the page, leaving us with:

1. `h1` Page Title
2. `h3` Widget Title

This results in improperly nested headings, as per [WCAG 2.0 Guidelines](https://www.w3.org/TR/2012/NOTE-WCAG20-TECHS-20120103/G141):

> To facilitate navigation and understanding of overall document structure, authors should use headings that are properly nested (e.g., h1 followed by h2, h2 followed by h2 or h3, h3 followed by h3 or h4, etc.).

We would theoretically be able to use `h3` for the titles and retain proper nesting if there was a wrapper for all widgets that  included a `h2` title on it. Then the page structure would be: 

1. `h1` Page Title
2. `h2` Widget Area Title
3. `h3` Widget Title

... but there's no current way for users to edit the text of a title like that. That, plus the years of precedence seems like a valid reason to stick with `h2`. 

I'm going to close this issue for now, but keep the PR for an alternate text size open.

**Comment by roylindauer** [comment]
Widget titles should not be headings at all. If you want them to visually look like headings then there should be some utility classes, like <p class="h2">My Widget Title</p>. Widgets are not important and generally do not provide any value in regards to SEO or page hierarchy. If they do, then you could always use a filter to alter the tag. One of the first things our SEO team would ask for is to remove unnecessary headings such as the ones on widgets. 

It would be best to use headings sparingly especially when a content creator cannot manage them at all.
