### ISSUE TITLE
PHP Warning: Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by slaFFik** [WordPress/twentynineteen#659]
```
[23-Nov-2018 11:21:04 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in ...\wordpress\trunk\wp-content\themes\twentynineteen\header.php on line 37
```

I'm on WordPress Nightly Build, `5.0-RC1-43944`.

**Comment by joshfeck** [comment]
This error can be replicated:
- on a server with PHP 7.2
- by viewing a standard WP post that has a featured image set
- where `WP_DEBUG` is set to `true`

**Comment by glueckpress** [comment]
I left a comment in your PR, @joshfeck. 🙂

**Comment by kjellr** [comment]
Just noting that #679 is also open as a solution to this problem.

**Comment by garrett-eclipse** [comment]
I took a look at #661 compared to #679 and feel 661 is overkill which the count function can simply be removed as the value is already numeric. Also 679 reduces characters as it appends the class. Cheers
