### ISSUE TITLE
Separator before heading looks differently in the editor than on the front

### ISSUE THREAD

**Issue by gziolo** [WordPress/twentynineteen#660]
It would be nice to align the look of the following pair of blocks: a separator preceding a heading. This is how the look at the moment:

## Editor

![screen shot 2018-11-23 at 14 04 19](https://user-images.githubusercontent.com/699132/48945252-edf8c000-ef29-11e8-95c7-8f798ea509fb.png)

## Frontend

![screen shot 2018-11-23 at 14 09 17](https://user-images.githubusercontent.com/699132/48945253-edf8c000-ef29-11e8-8e02-9e5fe1eceac7.png)

**Comment by kjellr** [comment]
Some background here: when a heading block follows a separator block, we hide the small separator that comes with the heading:

https://github.com/WordPress/twentynineteen/blob/f37782211882ddf006155fdfb6984023c2af197c/sass/blocks/_blocks.scss#L621-L629

We could probably do something similar in the editor, too.

**Comment by gziolo** [comment]
> We could probably do something similar in the editor, too.

That would be great to replicate it in the editor 👍
