### ISSUE TITLE
Improve color selection

### ISSUE THREAD

**Issue by dartiss** [WordPress/twentynineteen#669]
The custom primary color can only be specified via a simple draggable color selector. I would like the ability, for example, to specify an RGB, for something a lot more precise. As it is, the current selector is rather a blunt tool as it's difficult to define anything other than a rough colour choice.

**Comment by kjellr** [comment]
Hi, @dartiss — we had a similar question recently:

https://github.com/WordPress/twentynineteen/issues/613

You can see the relevant answer there, but in general: the current color picker uses a similar approach to the one in Twenty Seventeen, and was implemented to encourage more accessible color choices.

I'm going to close this issue for the same reason#613 was closed, but feel free to follow up with more thoughts if you'd like.

**Comment by kjellr** [comment]
You should be able to check out the hex/rgb value by inspecting a link in your browser's inspector. 

We could theoretically display this in the customizer, but I think for most users that would just lead to questions around why that color value isn't editable directly. (We're also only focusing on bugs + translation now that we're in the Release candidate, and I don't think that qualifies as a bug).
