### ISSUE TITLE
Columns block shows non-first columns with margin-left

### ISSUE THREAD

**Issue by willdelphia** [WordPress/twentynineteen#673]
Non-first columns have margin-left of 30px above 600px page-width. Even though they are wrapping onto their own rows at 782px. This looks strange to my eye. I would expect all columns to be aligned once they break into 100% width and wrap. 

![ezgif-5-90aca7146894](https://user-images.githubusercontent.com/4534359/49039286-fa2c8980-f184-11e8-8eb5-375812743874.gif)

**Comment by kjellr** [comment]
Thanks! #674 is a potential fix for this. 

Also, for completeness: I believe this is the same issue that was mentioned over here on Trac: https://core.trac.wordpress.org/ticket/45369
