### ISSUE TITLE
Count shouldn't be used on a numeric

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/twentynineteen#678]
Hello,

Minor issue with the use of count on a numeric, specifically the responses count used to add the .has-discussion class to the post. The use of count() throws a warning which ends up in the class in HTML;
Warning: count(): Parameter must be an array or an object that implements Countable in /app/public/wp-content/themes/twentynineteen/header.php on line 37
![screen shot 2018-11-27 at 4 22 15 pm](https://user-images.githubusercontent.com/8726005/49120208-a000f680-f260-11e8-8e48-956169eeee4c.png)

The count function can simply be removed from here as the attribute is already an integer, the line;
https://github.com/WordPress/twentynineteen/blob/master/header.php#L40

PR coming.

Cheers

**Comment by kjellr** [comment]
Hey @garrett-eclipse — this appears to be the same issue as #659, so I'm going to close this one as a duplicate.
