### ISSUE TITLE
Determine whether or not to keep two separate readme files

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#689]
**EDIT 12/3/2018:** _We added a new `readme.txt` via #693, but we still need to figure out whether that should replace `README.md`, or whether we should keep two._

_Previous issue text:_

---

As of October 25, 2018, new themes submitted to the WordPress.org theme repository must provide a `readme.txt` in the following format: 

```
=== Theme Name ===
Contributors: (this should be a list of wordpress.org userid's)
Tags: left-sidebar, fixed-width, custom-background
Requires at least: 4.0
Tested up to: 4.3-alpha
Stable tag: 1.0.3
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html

Short description. No more than 150 chars.

== Description ==
Theme desc.

== Frequently Asked Questions ==

= A question that someone might have =

An answer to that question.

== Changelog ==

= 1.0 =
* Added new option

= 0.5 =
* Security bug addressed
* Changed thumbnail size

== Upgrade Notice ==

= 1.0 =
* Upgrade notices describe the reason a user should upgrade.  No more than 300 characters.

= 0.5 =

* This version fixes a security related bug.  Upgrade immediately.

== Resources ==
* magnify.jpg © 2014 Jane Doe, CC0
* supermenu.js © 2013-2015 James Today, MIT 
``` 

_References:_ 
https://make.wordpress.org/themes/handbook/review/required/#readme-txt-file
https://make.wordpress.org/themes/2015/04/29/a-revised-readme/

Our [current readme](https://github.com/WordPress/twentynineteen/blob/master/README.md) is in markdown format, which is standard for GitHub. We could either: 

- Reformat + rename our current readme to follow the new format (this will likely result in a hard-to-read readme for the GitHub repo, as new lines won't be preserved).
- Keep our current readme for Github, and add a new `readme.txt` file using this new format.

**Comment by allancole** [comment]
#693 adds a new `.txt` reademe file and updates the formatting and description. 

Moving this issue to the 5.0.1 milestone so that we can make a decision about either keeping two separate readme files in 2 different formats, or combining them and breaking the format for either TRT requirements or GitHub legibility. 

We also need to address wether we should include an FAQ section in the readme or not.

**Comment by kjellr** [comment]
This one will be taken care of in #710 — it keeps both readme files, but puts their content in sync.

**Comment by kjellr** [comment]
Closing this, since #710 has been merged. 👍
