### ISSUE TITLE
Un-rendered Tweets Get Cut Off

### ISSUE THREAD

**Issue by desrosj** [WordPress/twentynineteen#694]
I use Firefox as my primary browser and have the setting to "Block Tracking Attempts" on. This prevents Tweets from rendering when embedded and instead renders the tweet as a `<blockquote>`.

When this happens, the left side of the text is being cut off. The example below is from the [WordPress 5.0: A Gutenberg FAQ](https://ma.tt/2018/11/a-gutenberg-faq/) post on Matt's blog.

<img width="780" alt="screen shot 2018-11-29 at 10 46 58 pm" src="https://user-images.githubusercontent.com/359867/49267477-ba85cc00-f428-11e8-9350-15ebe64bab43.png">

**Comment by desrosj** [comment]
I can create a PR in tomorrow. But, looks like the negative left margin on `blockquote` is the culprit.

**Comment by kjellr** [comment]
Thanks, @desrosj. I think Matt's actually running a version from a couple weeks ago. The negative blockquote margins were removed in https://github.com/WordPress/twentynineteen/pull/582. 

I recreated the post on a test site running RC1, and do not see the issue: 

<img width="616" alt="screen shot 2018-11-30 at 9 40 59 am" src="https://user-images.githubusercontent.com/1202812/49295562-13368280-f484-11e8-8624-9350dd09fba5.png">

Closing for now, but feel free to ping me if you can recreate in RC1. Thanks!

**Comment by desrosj** [comment]
Thanks, @kjellr. Just tested on the latest and works for me. Thanks!

**Comment by kjellr** [comment]
Thanks for confirming!
