### ISSUE TITLE
Does the arrow after the .more link needs to be underlined?

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentynineteen#698]
The link with the default text "Continue reading" appears on the post list page when a Read more block is inserted in a post. The link is underlined and has an arrow behind it which is also underlined. In my honest opinion, 

1. the arrow should either not be underlined since there is a blank space between the text and the arrow or
2. there should be no space between the text and the arrow and everything should be underlined.

I'd prefer option 1.

Before:
![screenshot 2018-12-02 at 08 23 36](https://user-images.githubusercontent.com/5901923/49336947-9b935f80-f60b-11e8-82cf-35e128cd73c5.png)

After:
![screenshot 2018-12-02 at 08 24 38](https://user-images.githubusercontent.com/5901923/49336957-bcf44b80-f60b-11e8-94ca-44719c8109ce.png)

**Comment by richtabor** [comment]
I agree!
