### ISSUE TITLE
Custom background feature

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentynineteen#708]
The theme has no Customizer setting to add a custom background image. It is, however, [tagged](https://github.com/WordPress/twentynineteen/blob/99f1f818f317a9b99da3d7ec73862909ace86de4/style.css#L13) as having the custom background feature.

Is there a reason that the custom background feature is not supported? This is a core feature that is fairly easily added. It is supported by all default themes, except for Twenty Seventeen and Twenty Thirteen.

**Comment by joyously** [comment]
Look at the history, but I think someone already tried to add it and it wasn't accepted because of accessibility concerns on the color scheme. (managing contrast)

**Comment by LittleBigThing** [comment]
It is indeed a feature that can be used in &lsquo;surprising ways&rsquo;, creating potential problems for accessibility or issues by adding large images as a background.

But the use of a custom background can be versatile: one could add a subtle background pattern or a (repeated) background image on the bottom to customize the look of her/his site. These do not affect accessibility. 

The core feature works out-of-the-box. I seems to work fine with the theme. But it is a decision we need to make and it's about controlling the user's freedom. I think that one can also mess up things in the editor, maybe even more than before Gutenberg, by setting way too large fonts sizes, font and background colors, ...

I am not sure either. :-)
Adding the feature is not really a bloat, so see PR #709.

And if we don't use it, we should remove the tag.

**Comment by LittleBigThing** [comment]
A thought against adding the feature:

- The custom background image won’t be visible in the editor (at least, by default).

**Comment by kjellr** [comment]
Thanks, @LittleBigThing! This was left out intentionally, for reasons similar to why we left out a background color option: it opens the door to accessibility issues. It's true that users could upload images that work fine accessibility-wise, but on the other hand... we can't guarantee that'll be the case. If someone wanted to add this option, I could definitely see it in a simple child theme or plugin, but I'd like to avoid including it by default.

**Comment by allancole** [comment]
That `custom-background` tag was left in there by mistake @LittleBigThing. It gets removed in ready-for-merge PR here: https://github.com/WordPress/twentynineteen/pull/710/files#diff-82af3a992dd99d43d1fccbf4380772adL13
