### ISSUE TITLE
Add Mastodon to Social Icons

### ISSUE THREAD

**Issue by howtomakemyblog** [WordPress/twentynineteen#711]
Add Mastodon to Social Icons

**Comment by ntwb** [comment]
This would be required to be added to dashicons first, not directly to this theme.

Please create an issue on that repo: https://github.com/WordPress/dashicons/

**Comment by kjellr** [comment]
Closing this issue, since it's been ported over to Trac here: https://core.trac.wordpress.org/ticket/45943
