### ISSUE TITLE
Duplicated meta on single post page

### ISSUE THREAD

**Issue by rodica-andronache** [WordPress/twentynineteen#712]
Not sure if this is the desired behavior, but the meta appears twice on single post pages
![tn-duplicated](https://user-images.githubusercontent.com/3266155/49648722-9b41fc80-fa2f-11e8-8f91-3e12166cb893.jpg)

**Comment by pratikkry** [comment]
This issue can be resolved by removing author and date from single post entry footer.

**Comment by polishedwp** [comment]
It appears this is the design intent, however, I am not sure this is desirable: 
[Nineteen Demo](https://themes.getmotopress.com/2019/2018/03/12/it-was-perfectly-possible-and-often-even-more-convenient-to-drive-to-the-school-direct/)

**Comment by laurelfulford** [comment]
It looks like this has already been moved to the Core Trac repo (where we're fully moving Twenty Nineteen and all of its issues), so I'm going to close this copy:

https://core.trac.wordpress.org/ticket/45555
