### ISSUE TITLE
Navigation submenu back-button not semantic

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentynineteen#714]
he main nav submenu back button is implemented as a <span> tag instead of a semantic button. This means all of the useful information of a button is lost.

Solutions:
1) Use a button
2) Emulate all the button behaviour using ARIA

**Comment by anevins12** [comment]
Excuse me, I meant "as a `span`" tag

**Comment by allancole** [comment]
Ahhh yeah, this should have been caught in #41, but I think the `<span>` solution was introduced after that initial accessibility review and got missed.

**Comment by anevins12** [comment]
I see. Right now the submenu cannot be accessed by a keyboard

**Comment by kjellr** [comment]
This was addressed in https://github.com/WordPress/twentynineteen/pull/735. 👍
