### ISSUE TITLE
Navigation submenu causing background items to be focusable

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentynineteen#715]
The main navigation submenu appears as an overlay to the screen, but does not trap the keyboard focus to the submenu. This means you can focus on background items of the page and completely lose yourself

**Comment by allancole** [comment]
Can you provide a screen grab of this problem? I believe `:focus-within` should be preventing what you’ve described but if it isn’t, I might be misunderstanding the problem.

**Comment by anevins12** [comment]
Cannnot replicate
