### ISSUE TITLE
Touch events hijacked by accidental JS leak

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentynineteen#717]
The 'toggleSubmenuDisplay' function in 'touch-keyboard-navigation.js' contains an event that watches and manipulates _all_ touch events and not just those specific to the submenu.

This causes a problem for links, as the code tells the browser to go to the page destination on touch - meaning people need only try to scroll the page before getting redirected to the link destination. 

https://wordpress.org/support/topic/links-get-triggered-while-scrolling-on-mobile-devices/?view=all

**Comment by kjellr** [comment]
Closed via #721. Thanks!
