### ISSUE TITLE
Regression in Classic Block toolbar button glyphs

### ISSUE THREAD

**Issue by azaozz** [WordPress/twentynineteen#719]
https://github.com/WordPress/twentynineteen/commit/2bf71ce7c0aa00492442f2773bc9ed15389178e3 enforces `dashicons` for the toolbar button the "wrong way", by using `!important` :)
Button icons should be overridden one by one, like in `/wp-includes/css/editor.css` (and the theme should not set them unless adding other/new buttons).

!important suuuucks!! Especially when any interoperability with plugins is involved. That change breaks all Classic Block toolbar buttons that are using the TinyMCE glyphs. Now they all show as "broken font" boxes.

Also thinking we should remove all `!important` everywhere. They only bring incompatibilities and trouble ahead (unless, of course, they are absolutely necessary and there is no other way to achieve the same result).

**Comment by kjellr** [comment]
Ugh, thanks. Can you share a screenshot of where these icons break? We didn't find that in our testing. 

> Also thinking we should remove all !important everywhere. They only bring incompatibilities and trouble ahead (unless, of course, they are absolutely necessary and there is no other way to achieve the same result).

100% agreed on this. Twenty Nineteen's non-latin language support is built on `!important`, which is not a good idea. There's a ticket for rewriting that in #602. We'd already seen issues with the `!important` approach: https://github.com/WordPress/twentynineteen/commit/2bf71ce7c0aa00492442f2773bc9ed15389178e3 (via #685) was a quick fix for broken toolbar icons before 5.0 was released, but using `!important` is bound to break things in all sorts of other places too.

**Comment by azaozz** [comment]
Here's the same Classic Block with fixed icon font:

![mce-buttons-fixed](https://user-images.githubusercontent.com/743931/49699346-b0a65a80-fbd8-11e8-8093-8556d5823774.png)

**Comment by kjellr** [comment]
We're in the process of closing down this GitHub repository now that the theme is merged into core, so I've migrated this issue (along with a possible solution) over to Trac:

https://core.trac.wordpress.org/ticket/45731

I'm closing this issue a result. Please feel free to follow up in the new thread moving forward.
