### ISSUE TITLE
Add link to privacy page in footer

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentynineteen#72]
I think that it should be possible to easily display a link to the privacy policy.

It could be implemented "kind of automatically" using the [available functions from WP 4.9.6](https://make.wordpress.org/core/2018/05/17/changes-that-affect-theme-authors-in-wordpress-4-9-6/).

We have the possibility to assign a page as a privacy policy page. A link to that page can be displayed something like:

```
<?php if ( get_privacy_policy_url() ) {
    // some markup
    the_privacy_policy_link();
    // some more markup
} ?>
```

This would mean that the link is shown automatically once the page is set...

**Comment by LittleBigThing** [comment]
Related to #45

**Comment by 00travelgirl00** [comment]
In my opinion it should be an own menu, where the user can decide which points should be displayed. Some countries have stricter rules. In Germany for example we have to have two sites "Impressum" and the "privacy policy". 

As far as I understand the suggested code, it would only display the "privacy policy", which would be a problem for users in some countries.

**Comment by LittleBigThing** [comment]
I think one definite pro for this way is simplicity (decisions above options :-)).

I am not sure about what the Impressum is, but isn't that something for a widget area in the footer? #14 

Anyway, I just noticed that this is already in the theme, in about the same way... :-)

**Comment by 00travelgirl00** [comment]
Impressum is similar to privacy policy, just different content (contact details and responsibility
of the website and stuff like that and a must have in germany (and I think in EU as well)) and should always be displayed next to privacy policy. 

I like the new core function for GDPR and it would be great, that a defined GDPR-Page get displayed automatically in the theme. We just should make it easy for users, to add more pages if they need to, to match their country requirements without the knowledge of CSS, HTML or even PHP. 

1. So maybe an Setting Option to add more pages next to it

2. or the option to deactivate those function and the possibility to define an own footer Menu?

**Comment by carolinan** [comment]
There already is a link to the privacy policy page in footer.php.

**Comment by kjellr** [comment]
> There already is a link to the privacy policy page in footer.php.

Agreed — just for clarification's sake: are we discussing something in addition to what's here already?

https://github.com/WordPress/twentynineteen/blob/master/footer.php#L21

**Comment by LittleBigThing** [comment]
I think this issue can be closed. I did not realize that the privacy policy link was already there.

The only thing is that the check on the existence of the privacy policy function might be superfluous if the theme would check the WP version (for only 5+).

There are other issues where adding a nav menu and a widget area are being discussed.

**Comment by kjellr** [comment]
Ok, thanks for the clarification. 

> The only thing is that the check on the existence of the privacy policy function might be superfluous if the theme would check the WP version (for only 5+).

I'm note sure about this, but I do think the current solution works fine as is. We can pursue this in a separate issue if we'd like. Thanks, all!
