### ISSUE TITLE
Allow child theme to redeclare twentynineteen_image_filters_enabled()

### ISSUE THREAD

**Issue by hvianna** [WordPress/twentynineteen#722]
I would like to disable the featured image color filter by default in my child theme. I can change the `image_filter` setting default itself, but for it to work properly I also need to change the default value in the `twentynineteen_image_filters_enabled()` function in `template-functions.php`.

I can't redefine that function in my child theme though, because it's not wrapped in a `function_exists()` conditional.

**Edit:**
It seems I would need to redeclare the entire `twentynineteen_setup()` function. If not for individual functions, would you guys consider at least smaller conditional chunks? Or am I missing something?

**Comment by allancole** [comment]
Hi @hvianna, the easiest answer is to simply uncheck the image filter option in the customizer :-).

Additionally, I’m not sure it’s even possible to make the defaults for a theme option filterable. Those values are representative of information stored in the database. 

Let’s say you’re using the `2019` parent theme and you’ve saved a `true` value for the image_filter. When you switch to a child theme, a filter won’t be able to rewrite that saved value. 

A better approach might be to use something like [update_option()](https://developer.wordpress.org/reference/functions/update_option/), on theme activation so the child theme starts with the setting you prefer.

**Comment by grappler** [comment]
> A better approach might be to use something like update_option(), on theme activation so the child theme starts with the setting you prefer.

This approach is not very good and not allowed on WordPress.org.

Something like this though might work. Have not tested it.
```php
$theme_slug = get_option( 'stylesheet' );
add_filter( "option_theme_mods_{$theme_slug}", function( $value ) {
	if ( empty( $value['image_filter'] ) {
		$value['image_filter'] = 0;
	}
	return $value;
} );
```

**Comment by hvianna** [comment]
@grappler It works! Thank you so much!! I've learned one more hook today! 😄 👍

**Comment by grappler** [comment]
Great! I have fixed the typo.

Though it might not be bad to have a filter.
```php
function twentynineteen_image_filters_enabled() {
	return apply_filters( 'twentynineteen_image_filters_enabled', 0 !== get_theme_mod( 'image_filter', 1 ) );
}
```

**Comment by hvianna** [comment]
That would be awesome, yes! An even cleaner solution than having to redefine that function.

**Comment by kjellr** [comment]
👋 We're in the process of archive this repository over to Trac, so I've opened a new ticket to track the filter idea: https://core.trac.wordpress.org/ticket/45945

Thanks, all!
