### ISSUE TITLE
[i18n] Remove unnecessary HTML from translation string

### ISSUE THREAD

**Issue by pedro-mendonca** [WordPress/twentynineteen#725]
The string **`<span class="meta-nav">Published in</span><br><span class="post-title">%title</span>`** have too much unnecessary HTML that can perfectly be removed.
https://github.com/WordPress/twentynineteen/blob/master/image.php#L87

Should be something like **`Published in %s`** instead.

**Comment by grappler** [comment]
I don't think there is a good solution other then changing the sentence structure. Related discussion to HTML in strings: https://github.com/WordPress/twentynineteen/pull/274

**Comment by kjellr** [comment]
We're in the process of closing this repository and migrating over to the core WordPress Trac, so I'm going to close this PR in favor of the discussion happening here: 

https://core.trac.wordpress.org/ticket/45473

Please feel to weigh in on that thread! We could use your expertise.

**Comment by pedro-mendonca** [comment]
Thanks for the headsup @kjellr
