### ISSUE TITLE
Mobile Menu: Console errors when clicking on empty links

### ISSUE THREAD

**Issue by kjellr** [WordPress/twentynineteen#726]
When using the touch menu, I'm seeing frequent errors related to `ariaItem.getAttribute` and `event.target.nextItem.matches`. Those are logging console errors when their value is `null`:

<img width="917" alt="screen shot 2018-12-11 at 8 48 48 am" src="https://user-images.githubusercontent.com/1202812/49804824-97f58c00-fd21-11e8-9f5f-237bc5e39b99.png">

To reproduce: 

- View a Twenty Nineteen site using the iOS, Firefox, or Chrome device simulators.
- Click on a link that points to `#`. 
- Check the console for errors.

**Comment by allancole** [comment]
Pretty sure this will get fixed when #721 is merged :-).

**Comment by kjellr** [comment]
@allancole I'm actually seeing them [in that branch](
https://github.com/WordPress/twentynineteen/pull/721#pullrequestreview-183685259), too.

**Comment by kjellr** [comment]
We're in the process of closing down this GitHub repository now that the theme is merged into core, so I've migrated this issue over to Trac at the link below. I'm closing this issue a result. Please feel free to follow up in the new thread moving forward:

https://core.trac.wordpress.org/ticket/45903

Thanks!
