### ISSUE TITLE
comments don't match CSS

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#73]
https://github.com/WordPress/twentynineteen/blob/7b1170c700b51ccc89479a5552c97102832b2d77/style.css#L1386-L1407

The CSS and the comments do not match.

**Comment by kjellr** [comment]
This specific instance is due to the way the Sass files are compiled. I'm going to close for now, as this will be solved one way or another when we align on whether or not to use Sass (and agree on a Sass compiler method, if we go that route).
