### ISSUE TITLE
Keyboard menu showing with touch menu on Mobile

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentynineteen#731]
Mobile devices can trigger hover events as well as touch events and because of this, users can sometimes be shown both keyboard and touch menus in the same scenarios. 

![731](https://user-images.githubusercontent.com/2318561/49908189-4cea8e80-fe71-11e8-93a2-38a8e012c12d.gif)

Context: https://wordpress.org/support/topic/header-menu-more-button-on-mobile/?view=all

Steps to replicate (either one of the following):
1) Press and hold the 3 dot button
2) Press the 3 dot button, then on the touch menu press + hold + drag down the "back" button

**Comment by kjellr** [comment]
I'm able to reproduce this one iOS (but only on screens that have no featured image for some reason):

![menu-hover](https://user-images.githubusercontent.com/1202812/49943023-d7a0ad00-feb4-11e8-9746-459324f17244.gif)

1. Press and hold on the button (in the case above, triggering a quick look)
2. Close the menu by hitting the back button
3. The desktop menu is visible

@allancole is it possible to have javascript tell the hover menus to deactivate when someone pushes the back button perhaps? We'd likely need to add a special class or something though. 🤔

**Comment by laurelfulford** [comment]
Closing this ticket, as it's been moved to Core Trac here: https://core.trac.wordpress.org/ticket/45905
