### ISSUE TITLE
Packagist and NPMJS

### ISSUE THREAD

**Issue by Hasan0ff** [WordPress/twentynineteen#732]
Hi.
First of all, I would like to take off my hat in front of everyone who had contributed to the wordpress during the last 15 years. 

I've been involved in many wordpress projects in the last 10 years but mainly been leeching off. However, after reading the gutenberg handbook (https://wordpress.org/gutenberg/handbook/) i decided that it's time to contribute.

i was quite skeptical at first when the gutenberg was introduced into 5.0 and quite confused why it has been done. i read through all the negative comments at wptavern and other websites which had led me to even think about forking out to classicpress. but i changed my mind after going through the handbook and understanding the advantages that blocks are going to bring to wordpress ecosystem.

My main issue and criticism over the years with wordpress was the way database structured. The projects which i was personally involved with had problems when around 3k-4k concurrent users used a single blog with large number of posts (in hundreds of thousands). The lag was visible especially when 2-3 meta fields were needed on every single post. The load time would sometimes spike up to 5-6 seconds or even more. Recently, i was thinking about moving to laravel because of negative comments about gutenberg (i think most people are still thinking that gutenberg is just an editor project but its much more than that).

i believe that introducing blocks and making them part of the post_content is an excellent idea as with time blocks could replace meta datas. at the same time, a single content query is enough to bring back the information that previously needed more than that (additional 2-3 postmeta queries).

Sorry for a long rant as anyone who had read this have wasted time which could be used in much more productive way. Now back to my single and most important question.
After reading the handbook, i checked the 2019 theme and saw that theme loaded packages from NPMJS and i assume we will be able to use composer too. Am I right?

**Comment by anevins12** [comment]
Sorry for not being clear, the reviews section is the place for writing a review: https://wordpress.org/support/theme/twentynineteen/reviews/#new-post

Github here is great for raising and tracking bugs
