### ISSUE TITLE
Baskerville Old Face is a poor font choice for Windows

### ISSUE THREAD

**Issue by Rarst** [WordPress/twentynineteen#737]
As soon as theme started popping out in the wild I've noticed that content text is really hard for me to read on Windows.

The highest priority font in stack is Baskerville Old Face and it seems to be a really strange choice. This font is:
- primarily meant for headings (theme doesn't use it for headings at all)
- renders really poorly at smaller sizes (mix of thick and thin strokes)
- does not have any weights (no bold, no italic)
- is not a unicode font, barely has couple hundred symbols of basic latin

If text in another language is displayed it shows up as ugly mix of Garamond with chunks of Baskerville Old Face for latin letters.

Was this a purposeful design decision or just something overlooked?

PS changing site language seems to override font stack altogether to sans-serif?

**Comment by Rarst** [comment]
Here is what it looks like on my machine:

![twenty-nineteen-baskerville](https://user-images.githubusercontent.com/737584/50020525-e97e6f00-ffde-11e8-8f90-f303ae04b233.png)

Especially note how strange italic looks because there isn't one in the font, system just messes with regular weight to fake it.

Here is example of some non-latin text. It almost entirely falls back to Garamond with Baskerville leaking through in latin abbreviation there:

![twenty-nineteen-garamond](https://user-images.githubusercontent.com/737584/50020668-63aef380-ffdf-11e8-8174-984fb9c7b462.png)

I found background on language switches and I feel tad weird that stack changes _entirely_ from serif to sans-serif. That's pretty much a different design conditional on what language site is set to.

**Comment by justintadlock** [comment]
I was just chatting about this and decided to look for a ticket.  It's really tough for me to read the Baskerville Old Face in body copy.  The dark and light strokes throw me off.

**Comment by kjellr** [comment]
I've opened a Trac issue for this ticket, along with a patch to remove Baskerville Old Face from the stack. I'm going to close this issue in the meantime, so please follow up there with any comments/suggestions: 

https://core.trac.wordpress.org/ticket/45881

Thanks everyone!
