### ISSUE TITLE
Convert references to 'classic editor' and 'block editor' to proper nouns

### ISSUE THREAD

**Issue by faisal-alvi** [WordPress/twentynineteen#739]
I have raised this issue after recommendation by @swisspidy [here](https://core.trac.wordpress.org/ticket/45634#comment:6)

**Comment by faisal-alvi** [comment]
#740

**Comment by kjellr** [comment]
Thanks for opening this here, @faisal-alvi. We're in the process of shutting down this GitHub repository now that the theme has been merged into core, and so we should move this discussion back into the original thread on Trac. Apologies for the back and forth!

https://core.trac.wordpress.org/ticket/45634#comment:9
