### ISSUE TITLE
Two column block: sub-blocks not aligned in mobile view

### ISSUE THREAD

**Issue by miwojc** [WordPress/twentynineteen#742]
left hand side sub-block (block inside a block) has margins: 22px right and 22px bottom, while right hand side sub-block has margins: 32px left. The difference in margins causes that blocks in mobile view look not aligned?

wordpress: Version 5.0.1
twenty nineteen: Version: 1.0

backend view:
![image](https://user-images.githubusercontent.com/32404415/50046924-e08eab80-0079-11e9-9a60-352fde27d6f9.png)

firefox inspector view left sub-block: 
![image](https://user-images.githubusercontent.com/32404415/50046884-de781d00-0078-11e9-866c-436964068d92.png)

right sub-block:
![image](https://user-images.githubusercontent.com/32404415/50046886-ef289300-0078-11e9-8bda-c0c3dbc46eaf.png)

firefox mobile view (iPad):
![image](https://user-images.githubusercontent.com/32404415/50046905-52b2c080-0079-11e9-89a7-a7088c093080.png)

**Comment by kjellr** [comment]
Thanks for the report, @miwojc. After doing some digging, I believe this is bug with Gutenberg, not just in the Twenty Nineteen theme. 

There appears to be work on this issue in the following Gutenberg tickets: 
https://github.com/WordPress/gutenberg/pull/12199
https://github.com/WordPress/gutenberg/issues/13035
https://github.com/WordPress/gutenberg/pull/12816

I'm going to close this issue as a result, but if this issue persists, please feel free to open up a new issue over on Trac. (Now that the theme has launched, we'll be retiring this GitHub repository soon). 

https://core.trac.wordpress.org/newticket

Thank you!
