### ISSUE TITLE
No version number in doc block

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/twentynineteen#743]
Is there any reason / discussion about not adding version numbers like in Twenty Seventeen?
https://github.com/WordPress/twentyseventeen/issues/72

If yes, can someone please point me to this decision / discussion / etc. - Thank you!

**Comment by kjellr** [comment]
I do not believe that's intentional. Feel free to open up a PR!

**Comment by Zodiac1978** [comment]
Ping @luminuu

**Comment by laurelfulford** [comment]
Closing this ticket, as it's been moved to Trac here: https://core.trac.wordpress.org/ticket/45908
