### ISSUE TITLE
.button class doesn't override link color

### ISSUE THREAD

**Issue by crunnells** [WordPress/twentynineteen#746]
I noticed this one the [theme demo site](http://2019.wordpress.net/) when I tried to change the "Get in touch" button into a link. If you put a link inside of an element with the `.button` class, the link color is the same color blue as the background, so the text can't be read. The same thing occurs when you try `<a href="#" class="button">`, so we'll need to have an override on the link color so that it's readable.

**Comment by laurelfulford** [comment]
Closing this ticket, as it's been moved over to Trac here: https://core.trac.wordpress.org/ticket/45904
