### ISSUE TITLE
Search widget input field width is too narrow on wide screens

### ISSUE THREAD

**Issue by crunnells** [WordPress/twentynineteen#747]
At screens below ~600px, the search input field is 100% of the parent container, but above that it changes to `width: auto;` which causes it to shrink to ~170px. I suggest we make that a little larger by removing `auto` and setting a `max-width` in the CSS.

Below 598px:
<img width="606" alt="screen shot 2018-12-18 at 10 14 05 am" src="https://user-images.githubusercontent.com/4297811/50180471-c76e4080-02ad-11e9-94c4-d7228948c581.png">

Above 600px:
<img width="634" alt="screen shot 2018-12-18 at 10 14 24 am" src="https://user-images.githubusercontent.com/4297811/50180484-cfc67b80-02ad-11e9-8c82-d21c5c50f32f.png">

**Comment by kjellr** [comment]
Thanks, @crunnells! We're in the process of closing down this GitHub repository now that the theme is merged into core, so I've migrated this issue over to Trac:

https://core.trac.wordpress.org/ticket/45878
