### ISSUE TITLE
Firefox Dropcap margin mismatch [Proposed Solution]

### ISSUE THREAD

**Issue by josephdickson** [WordPress/twentynineteen#749]
Hi everyone,
Firefox renders the dropcap text roughly 0.2em higher than in Chromium.
![2018-12-21-004325_1920x1080_scrot](https://user-images.githubusercontent.com/9701927/50334075-0b369500-04bc-11e9-9442-a51436a6ef8c.png)

Possible solution: Detect Firefox and adjust top margin by 0.2em from the 0em set in the CSS as seen below.

```
.entry .entry-content .has-drop-cap:not(:focus)::first-letter {
margin: 0.2em 0.25rem 0;
}

```
However, making this change would break other browsers. Is there a way to make this fix specific only to Firefox?

**Comment by josephdickson** [comment]
With a little help from @electmikemann (Twitter) I found a solution that I'd like to propose for a future update.

![solution](https://user-images.githubusercontent.com/9701927/50365553-f85aa980-0529-11e9-8f17-d58d54e35064.png)

This prefix targets Firefox and is ignored by other browsers.

`@-moz-document url-prefix() {
	.entry .entry-content .has-drop-cap:not(:focus)::first-letter {
  	margin-top: 0.2em;
	}
}`

Source: [stackoverflow.com](https://stackoverflow.com/questions/6737175/firefox-specific-margin)

**Comment by kjellr** [comment]
Thanks, @josephdickson! We're in the process of closing down this GitHub repository now that the theme is merged into core, so I've migrated this issue over to Trac: 

https://core.trac.wordpress.org/ticket/45876
