### ISSUE TITLE
After a word written in italic, inverted commas appear wrongly

### ISSUE THREAD

**Issue by joaodemancelos** [WordPress/twentynineteen#752]
On my webpage, I noticed that after I insert a word written in italic, the following inverted commas appear incorrectly (facing right instead of left). The address of my website: http://mancelos.com. See section d), the link to: "What kind of evil you got in there? Memory and trauma in Jonathan Demme’s Beloved“

**Comment by kjellr** [comment]
Hi @joaodemancelos! Thanks for the report. I can reproduce this with all themes, so I'm not sure it seems like something that'd be better tackled as part of Gutenberg. I've opened an issue here to track it, and will close this one in the meantime: 

https://github.com/WordPress/gutenberg/issues/13240

Thank you!
