### ISSUE TITLE
where are the SCSS files for the style-RTL.css

### ISSUE THREAD

**Issue by JQOz** [WordPress/twentynineteen#757]
Hi,
whare the SCSS files for the style-RTL.css.

Or 

should we use the normal scss files to generate the style-rtl.css, if yes how?

Thanks

**Comment by peterwilsoncc** [comment]
@JQOz,

A build step is used to generate the style-rtl.css file from the regular scss files, it does so by reversing floats, left and right margins, and other items specified by left and right.

In some cases it's disabled with some line comments which you can see in the scss files, for example where left/right is a utility class specifying direction.

https://github.com/WordPress/twentynineteen/blob/ece29078abcb92370896327eabd331577a7ddfe9/sass/blocks/_blocks.scss#L49-L55

> should we use the normal scss files to generate the style-rtl.css, if yes how?

Yes, to generate them run the script `npm run build:rtl` after building `style.css` from the scss files. 

`npm run build` will complete all the steps required to build the CSS, including the rtl styles.

**Comment by kjellr** [comment]
Thanks for the thorough answer, @peterwilsoncc! 

I'm going to close this issue, but please feel free to follow up here or in the #core-themes slack channel if there are further questions.

**Comment by JQOz** [comment]
Thank you!
