### ISSUE TITLE
duplicate, more specific CSS

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#77]
There is a `Blocks` section in the CSS that has the `entry-content` class at the front of all selectors. Some rules are duplicates of earlier rules, but more specific. Can these rules work without the `entry-content` class or do they need to be that specific?

**Comment by khleomix** [comment]
this is affecting the caption for Gutenberg-inserted images:
caption is not centered in Gutenberg-inserted image. `.entry-content .wp-block-image figcaption` is overriding `.wp-block-image figcaption`

**Comment by kjellr** [comment]
The `.entry-content` class is required to make sure the blocks that have no classnames inherit styles correctly (`p`, `h1`, etc.). Outside of those, there may be some specific cases that we can address, however I'd suggest we address those in individual issues on Trac at this point. 

I'm going to close this issue for now, but feel free to open up a Trac issue for specific enhancements/code cleanup in this area.
