### ISSUE TITLE
RTL css separate?

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#78]
It is easier to maintain RTL styles if they are in the same file as the other styles. There is also less duplication.

**Comment by audrasjb** [comment]
Hi,
I believe RTL styles are generated by SASS.

**Comment by joyously** [comment]
Well, the rtl.css file is empty. And it is still easier to maintain when they are in the same file.

**Comment by nielslange** [comment]
@joyously I assume this issue can be closed now that #169 got merged, correct? With #169 the RTL CSS also gets created on the fly.

**Comment by joyously** [comment]
No, it's still a question about what's the most maintainable approach.
One way you have the RTL style in the same file, following the normal CSS. It is obvious as things are changed that the RTL should be considered as well.
The other way you have the RTL style in a different file, and the developer has to remember to check if changes affect it. There is also more code to check for RTL and load the other file.

**Comment by grappler** [comment]
I find the current method the best way. 

> There is also more code to check for RTL and load the other file.

If the site is RTL then only the `style-rtl.css` will loaded not both. This is done by adding this line of code `wp_style_add_data( 'twentynineteen-style', 'rtl', 'replace' );`

**Comment by kjellr** [comment]
I'm closing this issue for now, since there are no current plans to change our RTL CSS strategy. Other default themes generally include RTL in a separate file, and @allancole clarified some of the current RTL behavior here: https://github.com/WordPress/twentynineteen/issues/257#issuecomment-432372937
