### ISSUE TITLE
Jetpack display issues

### ISSUE THREAD

**Issue by dartiss** [WordPress/twentynineteen#8]
I'm sure this is more an issue with Jetpack but as an awful lot of theme users are going to using it, I don't know if this is something worth fixing with the CSS of Twenty Nineteen.

Two immediate things spring out...

1. Akismet message on comments is shown left justified, ignoring other post boundaries. See bottom of https://pento.net/2018/10/04/wordpress-5-0-needs-you/, for example. Here's a screenshot from my own test site...

<img width="1667" alt="screenshot 2018-10-17 at 10 13 07" src="https://user-images.githubusercontent.com/14928971/47076156-fc9adb80-d1f5-11e8-8a97-9ff367be3d50.png">

2. Related posts are a mess. Thumbnails are missing and, again, everything is left justified - see screenshot below...

<img width="1697" alt="screenshot 2018-10-17 at 10 12 58" src="https://user-images.githubusercontent.com/14928971/47076186-0e7c7e80-d1f6-11e8-8c62-58bc0c86aca7.png">

Tested on...
WordPress: 4.9.8
Gutenberg: 3.9.0
Jetpack: 6.6.1
Twenty Nineteen: 1.0 (dated October 17th)

**Comment by kjellr** [comment]
_Merging #86 into this issue for organization's sake_

---

via @bph

The related post section below the post
[ ]  isn't aligned with the rest of the content.
[ ] doesn't leave enough white space between thumbnail and title

![screen shot 2018-10-16 at 7 18 27 pm](https://user-images.githubusercontent.com/39980/47052910-9459e480-d178-11e8-9a36-091d2aedb1f6.png)

**Comment by nielslange** [comment]
Close as Jetpack will handle theme support within the plugin, as mentioned in #202 (comment).
