### ISSUE TITLE
horizontal rule is barely there

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#83]
The styles for `<hr>` make the element very short. When I look at the styles, it says 
`max-width: 2.25em`
That's tiny and would be very unexpected for legacy content.

**Comment by kjellr** [comment]
The theme actually ships with three `hr` styles, all accessible via Gutenberg block variants:

![screen shot 2018-10-17 at 12 41 40 pm](https://user-images.githubusercontent.com/1202812/47102203-121a0080-d20a-11e8-950e-6d0f80b40db5.png)

For the purpose of preserving the expected visual appearance in legacy content, I'm fine with reverting to the middle version for `hr`s that don't have the `wp-block-separator` class.

**Comment by joyously** [comment]
That would be a good way to do it.

**Comment by mrwweb** [comment]
The default style is redundant with the line above the H2. Given that HR's and H2s are both used to denote major changes in content within a document, it makes sense for the theme to support them used in conjunction out of the box. I'd flip the 1st and 2nd styles.

**Comment by laurelfulford** [comment]
Closing this ticket, as it's been moved to Trac here: https://core.trac.wordpress.org/ticket/45912
