### ISSUE TITLE
I do not like the blue images

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#85]
Is this going to be a color choice? And a toggle?

**Comment by fabiankaegy** [comment]
I would like the setting to be available in the color section inside the Customizer. 

I'm also up for implementing it once @kjellr  or @allancole approve that this is where this setting should go.

**Comment by kjellr** [comment]
The blue overlay should definitely be a setting — I'll take a look at those PRs later today. 

> Should the setting change the "primary-color" throughout the theme? i.e. Left border of pullquote, link color, button background etc.?

Yes, but I agree that that we should include some sort of contrast check is we do that. Because of the complexities involved in that, it should be a separate PR.

**Comment by fabiankaegy** [comment]
> The blue overlay should definitely be a setting — I'll take a look at those PRs later today.
Great. This one only affects the featured image overlay color

**Comment by LittleBigThing** [comment]
I think that we should first consider browser compatibility and possible fallbacks before implementing this customization. See #121 and #124.

**Comment by designsimply** [comment]
Closing this issue in favor of consolidating to https://github.com/WordPress/twentynineteen/issues/191 which is marked as a task and also has a clear unbiased title.

Feel free to keep using this issue to hash out ideas and discuss even after it is closed! 

One of my goals when helping with triage is to help organize open issues to be more actionable and short when and where I can.
