### ISSUE TITLE
Related Posts: Alignment & whitespace

### ISSUE THREAD

**Issue by bph** [WordPress/twentynineteen#86]
The related post section below the post 

- [ ]  isn't aligned with the rest of the content. 
- [ ] doesn't leave enough white space between thumbnail and title 
![screen shot 2018-10-16 at 7 18 27 pm](https://user-images.githubusercontent.com/39980/47052910-9459e480-d178-11e8-9a36-091d2aedb1f6.png)

**Comment by kjellr** [comment]
Thanks @bph — I'm going to merge this one into #8 since the fix is related.
