### ISSUE TITLE
Centered captioned images are not centered

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#87]
The caption is centered under the image, but the image is not centered in the content.

**Comment by khleomix** [comment]
@kjellr I'll take this up if no one's working on it.

**Comment by khleomix** [comment]
caption is not centered in Gutenberg-inserted image.  `.entry-content .wp-block-image figcaption` is overriding `.wp-block-image figcaption` 
@kjellr should this be a separate issue? If so, I'll create one for it if it's not yet addressed.

**Comment by joyously** [comment]
I wrote one about having duplicate CSS and too specific selectors.

**Comment by khleomix** [comment]
@joyously added my comment to your issue for more reference. Thanks.
