### ISSUE TITLE
full content versus excerpts

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#89]
Can we make an option to choose full content or excerpts?
Full content is not that good for SEO, and really bad user experience on search page.

**Comment by frankew** [comment]
Would this be an appropriate use of the ['blog-display' field in Jetpack's Content Options](https://en.support.wordpress.com/customizer/content-options/#blog-display)? 

The theme already makes use of content options for 'post-details' and 'featured-images'.
