### ISSUE TITLE
<big> is too big

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#90]
The `<big>` tag is too big, and is one size only, so nested tags are not bigger. Note how the spacing is all awry.

![big-tag-too-big](https://user-images.githubusercontent.com/7957680/47053836-72f6f980-d174-11e8-96f5-98f0fbab5962.jpg)

**Comment by nielslange** [comment]
@kjellr or @allancole Can one of your close all merged issues, to retain an overview of the open issues? If needed, I'm happy to go through all issues and provide a list of merged issues. 😉

**Comment by kjellr** [comment]
@nielslange Thanks! I'll do a quick scrub of these today. 

This particular one is closed via #137.

**Comment by nielslange** [comment]
Thank, @kjellr!
