### ISSUE TITLE
gallery shortcode columns not working

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#91]
There are styles for gallery shortcode columns, but it is incorrect.
For 1 column, the images are centered, but the captions are left. There is no space between images with no captions.
For 2 columns, 3 are shown.
For 3 columns, 2 are shown.
For 4 through 9 columns, it looks almost like 1 column, but the images are very far left on 4, a little more right on 5, more right on 6, etc., but all have just 1 image instead of 4, 5, 6, etc.

**Comment by briannaorg** [comment]
I'm working on this one.

**Comment by kjellr** [comment]
@joyously would you mind providing a screenshot here so we can get a better sense of the issue? Thanks!

**Comment by briannaorg** [comment]
I've submitted a fix for this - https://github.com/WordPress/twentynineteen/pull/130

**Comment by joyously** [comment]
Here is what it looked like on my test site
![gallery-test](https://user-images.githubusercontent.com/7957680/47105414-75576300-d209-11e8-8686-2afe79bfa857.jpg)

**Comment by kjellr** [comment]
Fixed via https://github.com/WordPress/twentynineteen/commit/918a410b23d8342a0740f5e17506b8bea770ef75

**Comment by kjellr** [comment]
@allancole Now that I'm looking at this again, it's not looking fixed to me:

<img width="1251" alt="screen shot 2018-10-24 at 10 06 52 pm" src="https://user-images.githubusercontent.com/1202812/47471660-4d539b00-d7d9-11e8-9112-c745031f039f.png">

(Using the [theme unit test](https://github.com/WPTRT/theme-unit-test) sample posts)

**Comment by kjellr** [comment]
Closing this one in favor of the newer issue, #531.
