### ISSUE TITLE
path to template part is wrong

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#97]
https://github.com/WordPress/twentynineteen/blob/be850d11ee31434ad700db518ff8570f82e65b9c/search.php#L51
and
https://github.com/WordPress/twentynineteen/blob/be850d11ee31434ad700db518ff8570f82e65b9c/archive.php#L45

reference a template part that does not exist.
It would be better for users if this was not so nested. In order for a child theme to replace a template part, the same directory structure has to be made. Flatter is better. Also, calling one folder `post` is a little odd considering it should work for any post type.

**Comment by yingles** [comment]
I updated the path to the `content-none.php` file in `search.php` and `archive.php`. Naming is not my forte so I'm not sure of a good alternative for the `template-parts/post` directory.
